"""Add options to category_attributes

Revision ID: 06c8cbb567e8
Revises: 7f96a36fba92
Create Date: 2025-12-05 06:47:51.112845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06c8cbb567e8'
down_revision = '7f96a36fba92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_attributes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Override global options if set'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_attributes', schema=None) as batch_op:
        batch_op.drop_column('options')

    # ### end Alembic commands ###
