"""添加产品英文名称字段name_en

Revision ID: 0db29e5b5489
Revises: a408719a2f2c
Create Date: 2025-12-18 03:09:29.047962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db29e5b5489'
down_revision = 'a408719a2f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=200), nullable=True, comment='产品英文名称'))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               comment='产品中文名称',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='产品中文名称',
               existing_nullable=False)
        batch_op.drop_column('name_en')

    # ### end Alembic commands ###
