"""add_realname_field_to_users

Revision ID: 1242638ab8f0
Revises: 448a77c4d244
Create Date: 2025-12-17 14:32:54.947430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1242638ab8f0'
down_revision = '448a77c4d244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('realname', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('realname')

    # ### end Alembic commands ###
