"""扩展发货单表-添加仓库物流财务字段

Revision ID: 141feba69c64
Revises: c3fe645260ed
Create Date: 2025-12-19 02:44:08.615892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '141feba69c64'
down_revision = 'c3fe645260ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_name', sa.String(length=100), nullable=True, comment='主供应商名称'))
        batch_op.add_column(sa.Column('fnsku', sa.String(length=50), nullable=True, comment='亚马逊FNSKU'))
        batch_op.add_column(sa.Column('msku', sa.String(length=100), nullable=True, comment='商家SKU(MSKU)'))
        batch_op.add_column(sa.Column('asin', sa.String(length=20), nullable=True, comment='ASIN码'))
        batch_op.add_column(sa.Column('marketplace_listing_id', sa.String(length=100), nullable=True, comment='市场Listing ID'))
        batch_op.add_column(sa.Column('warehouse_matched_qty', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='配对数量'))
        batch_op.add_column(sa.Column('warehouse_received_qty', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='已收数量'))
        batch_op.add_column(sa.Column('warehouse_pending_qty', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='待收数量'))
        batch_op.add_column(sa.Column('shelf_location', sa.String(length=50), nullable=True, comment='货架位置'))
        batch_op.add_column(sa.Column('package_no', sa.String(length=50), nullable=True, comment='箱号'))
        batch_op.add_column(sa.Column('barcode', sa.String(length=100), nullable=True, comment='箱码/条码'))
        batch_op.add_column(sa.Column('unit_volume', sa.DECIMAL(precision=10, scale=6), nullable=True, comment='单件体积(m³)'))
        batch_op.alter_column('supplier_id',
               existing_type=sa.INTEGER(),
               comment='主供应商ID',
               existing_comment='供应商ID',
               existing_nullable=True)

    with op.batch_alter_table('shipment_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_warehouse_id', sa.Integer(), nullable=True, comment='发货仓库ID'))
        batch_op.add_column(sa.Column('origin_warehouse_name', sa.String(length=100), nullable=True, comment='发货仓库名称'))
        batch_op.add_column(sa.Column('origin_warehouse_type', sa.String(length=20), nullable=True, comment='发货仓库类型(self/factory/supplier)'))
        batch_op.add_column(sa.Column('origin_warehouse_address', sa.Text(), nullable=True, comment='发货仓库地址'))
        batch_op.add_column(sa.Column('is_factory_direct', sa.Boolean(), nullable=True, server_default='false', comment='是否工厂直发'))
        batch_op.add_column(sa.Column('destination_warehouse_id', sa.Integer(), nullable=True, comment='收货仓库ID'))
        batch_op.add_column(sa.Column('destination_warehouse_name', sa.String(length=100), nullable=True, comment='收货仓库名称'))
        batch_op.add_column(sa.Column('destination_warehouse_code', sa.String(length=50), nullable=True, comment='收货仓库编码'))
        batch_op.add_column(sa.Column('destination_warehouse_type', sa.String(length=20), nullable=True, comment='仓库类型(fba/third_party/self)'))
        batch_op.add_column(sa.Column('destination_warehouse_address', sa.Text(), nullable=True, comment='收货仓库地址'))
        batch_op.add_column(sa.Column('fba_shipment_id', sa.String(length=100), nullable=True, comment='FBA发货计划ID'))
        batch_op.add_column(sa.Column('fba_center_codes', postgresql.ARRAY(sa.String()), nullable=True, comment='FBA中心编码数组'))
        batch_op.add_column(sa.Column('marketplace', sa.String(length=10), nullable=True, comment='市场站点(US/UK/DE/JP等)'))
        batch_op.add_column(sa.Column('warehouse_service_provider', sa.String(length=100), nullable=True, comment='仓储服务商'))
        batch_op.add_column(sa.Column('warehouse_contact', sa.String(length=50), nullable=True, comment='仓库联系人'))
        batch_op.add_column(sa.Column('warehouse_contact_phone', sa.String(length=20), nullable=True, comment='仓库联系电话'))
        batch_op.add_column(sa.Column('logistics_service_type', sa.String(length=50), nullable=True, comment='物流服务类型'))
        batch_op.add_column(sa.Column('freight_term', sa.String(length=20), nullable=True, comment='运费支付方式(prepaid/collect/third_party)'))
        batch_op.add_column(sa.Column('estimated_arrival_date', sa.Date(), nullable=True, comment='预计到货日期'))
        batch_op.add_column(sa.Column('actual_arrival_date', sa.Date(), nullable=True, comment='实际到货日期'))
        batch_op.add_column(sa.Column('warehouse_received_date', sa.DateTime(), nullable=True, comment='仓库签收时间'))
        batch_op.add_column(sa.Column('completed_date', sa.DateTime(), nullable=True, comment='完成时间'))
        batch_op.add_column(sa.Column('packing_method', sa.String(length=50), nullable=True, comment='包装方式(纸箱/托盘/散装)'))
        batch_op.add_column(sa.Column('volumetric_weight', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='体积重(kg)'))
        batch_op.add_column(sa.Column('chargeable_weight', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='计费重量(kg)'))
        batch_op.add_column(sa.Column('total_goods_value', sa.DECIMAL(precision=18, scale=2), nullable=True, comment='货物总价值'))
        batch_op.add_column(sa.Column('declared_value', sa.DECIMAL(precision=18, scale=2), nullable=True, comment='申报价值'))
        batch_op.add_column(sa.Column('freight_cost', sa.DECIMAL(precision=18, scale=2), nullable=True, comment='运费'))
        batch_op.add_column(sa.Column('insurance_cost', sa.DECIMAL(precision=18, scale=2), nullable=True, comment='保险费'))
        batch_op.add_column(sa.Column('handling_fee', sa.DECIMAL(precision=18, scale=2), nullable=True, comment='操作费'))
        batch_op.add_column(sa.Column('other_costs', sa.DECIMAL(precision=18, scale=2), nullable=True, comment='其他费用'))
        batch_op.add_column(sa.Column('total_logistics_cost', sa.DECIMAL(precision=18, scale=2), nullable=True, comment='物流总成本'))
        batch_op.add_column(sa.Column('vat_number', sa.String(length=50), nullable=True, comment='VAT税号'))
        batch_op.add_column(sa.Column('tax_rate', sa.DECIMAL(precision=5, scale=4), nullable=True, comment='税率'))
        batch_op.add_column(sa.Column('estimated_tax', sa.DECIMAL(precision=18, scale=2), nullable=True, comment='预估税费'))
        batch_op.add_column(sa.Column('actual_tax', sa.DECIMAL(precision=18, scale=2), nullable=True, comment='实际税费'))
        batch_op.add_column(sa.Column('total_purchase_cost', sa.DECIMAL(precision=18, scale=2), nullable=True, comment='采购总成本(从采购明细汇总)'))
        batch_op.add_column(sa.Column('profit_margin', sa.DECIMAL(precision=5, scale=4), nullable=True, comment='利润率'))
        batch_op.add_column(sa.Column('cost_allocation_method', sa.String(length=20), nullable=True, comment='成本分摊方式(volume/weight/quantity/value)'))
        batch_op.alter_column('shipping_method',
               existing_type=sa.VARCHAR(length=50),
               comment='运输方式(air/sea/express/land/sea_air)',
               existing_comment='运输方式(海运/空运/快递)',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_orders', schema=None) as batch_op:
        batch_op.alter_column('shipping_method',
               existing_type=sa.VARCHAR(length=50),
               comment='运输方式(海运/空运/快递)',
               existing_comment='运输方式(air/sea/express/land/sea_air)',
               existing_nullable=True)
        batch_op.drop_column('cost_allocation_method')
        batch_op.drop_column('profit_margin')
        batch_op.drop_column('total_purchase_cost')
        batch_op.drop_column('actual_tax')
        batch_op.drop_column('estimated_tax')
        batch_op.drop_column('tax_rate')
        batch_op.drop_column('vat_number')
        batch_op.drop_column('total_logistics_cost')
        batch_op.drop_column('other_costs')
        batch_op.drop_column('handling_fee')
        batch_op.drop_column('insurance_cost')
        batch_op.drop_column('freight_cost')
        batch_op.drop_column('declared_value')
        batch_op.drop_column('total_goods_value')
        batch_op.drop_column('chargeable_weight')
        batch_op.drop_column('volumetric_weight')
        batch_op.drop_column('packing_method')
        batch_op.drop_column('completed_date')
        batch_op.drop_column('warehouse_received_date')
        batch_op.drop_column('actual_arrival_date')
        batch_op.drop_column('estimated_arrival_date')
        batch_op.drop_column('freight_term')
        batch_op.drop_column('logistics_service_type')
        batch_op.drop_column('warehouse_contact_phone')
        batch_op.drop_column('warehouse_contact')
        batch_op.drop_column('warehouse_service_provider')
        batch_op.drop_column('marketplace')
        batch_op.drop_column('fba_center_codes')
        batch_op.drop_column('fba_shipment_id')
        batch_op.drop_column('destination_warehouse_address')
        batch_op.drop_column('destination_warehouse_type')
        batch_op.drop_column('destination_warehouse_code')
        batch_op.drop_column('destination_warehouse_name')
        batch_op.drop_column('destination_warehouse_id')
        batch_op.drop_column('is_factory_direct')
        batch_op.drop_column('origin_warehouse_address')
        batch_op.drop_column('origin_warehouse_type')
        batch_op.drop_column('origin_warehouse_name')
        batch_op.drop_column('origin_warehouse_id')

    with op.batch_alter_table('shipment_order_items', schema=None) as batch_op:
        batch_op.alter_column('supplier_id',
               existing_type=sa.INTEGER(),
               comment='供应商ID',
               existing_comment='主供应商ID',
               existing_nullable=True)
        batch_op.drop_column('unit_volume')
        batch_op.drop_column('barcode')
        batch_op.drop_column('package_no')
        batch_op.drop_column('shelf_location')
        batch_op.drop_column('warehouse_pending_qty')
        batch_op.drop_column('warehouse_received_qty')
        batch_op.drop_column('warehouse_matched_qty')
        batch_op.drop_column('marketplace_listing_id')
        batch_op.drop_column('asin')
        batch_op.drop_column('msku')
        batch_op.drop_column('fnsku')
        batch_op.drop_column('supplier_name')

    # ### end Alembic commands ###
