"""Check for pending changes

Revision ID: 144bc9ebfd67
Revises: 763e1e8a803e
Create Date: 2025-12-04 23:16:22.225133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '144bc9ebfd67'
down_revision = '763e1e8a803e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_dictionary_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_dictionary_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dict_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dict_id'], ['sys_dictionaries.id'], name=op.f('sys_dictionary_items_dict_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_dictionary_items_pkey'))
    )
    # ### end Alembic commands ###
