"""Enhance tax and supply models for declaration driven contract

Revision ID: 14f54365d002
Revises: c65ee950e9f1
Create Date: 2025-12-12 03:58:52.309433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f54365d002'
down_revision = 'c65ee950e9f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customs_declaration_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tax_customs_declarations', ['customs_declaration_id'], ['id'])

    with op.batch_alter_table('tax_customs_declarations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logistics_provider', sa.String(length=100), nullable=True, comment='物流服务商'))
        batch_op.add_column(sa.Column('shipping_no', sa.String(length=100), nullable=True, comment='提单号/运单号'))
        batch_op.add_column(sa.Column('shipping_date', sa.Date(), nullable=True, comment='发货日期'))
        # Modify this line to be nullable=True initially or provide server_default
        batch_op.add_column(sa.Column('source_type', sa.String(length=20), server_default='manual', nullable=False, comment='来源: manual, excel_import, api'))
        batch_op.add_column(sa.Column('source_file_url', sa.String(length=255), nullable=True, comment='原始文件路径'))

    with op.batch_alter_table('tax_customs_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True, comment='供应商ID'))
        batch_op.add_column(sa.Column('sku', sa.String(length=100), nullable=True, comment='SKU编码(冗余)'))
        batch_op.add_column(sa.Column('box_no', sa.String(length=50), nullable=True, comment='箱号'))
        batch_op.add_column(sa.Column('net_weight', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='净重(KG)'))
        batch_op.add_column(sa.Column('gross_weight', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='毛重(KG)'))
        batch_op.create_foreign_key(None, 'sys_suppliers', ['supplier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_customs_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gross_weight')
        batch_op.drop_column('net_weight')
        batch_op.drop_column('box_no')
        batch_op.drop_column('sku')
        batch_op.drop_column('supplier_id')

    with op.batch_alter_table('tax_customs_declarations', schema=None) as batch_op:
        batch_op.drop_column('source_file_url')
        batch_op.drop_column('source_type')
        batch_op.drop_column('shipping_date')
        batch_op.drop_column('shipping_no')
        batch_op.drop_column('logistics_provider')

    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('customs_declaration_id')

    # ### end Alembic commands ###
