"""Add data permission tables

Revision ID: 176400d0881c
Revises: 0fe0581e4a22
Create Date: 2025-11-23 04:35:09.981005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '176400d0881c'
down_revision = '0fe0581e4a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_permission_metas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['data_permission_metas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_permission_metas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_permission_metas_key'), ['key'], unique=True)

    op.create_table('role_data_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('category_key', sa.String(length=100), nullable=False),
    sa.Column('target_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resource_scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_data_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_data_permissions_role_id'), ['role_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_data_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_data_permissions_role_id'))

    op.drop_table('role_data_permissions')
    with op.batch_alter_table('data_permission_metas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_permission_metas_key'))

    op.drop_table('data_permission_metas')
    # ### end Alembic commands ###
