"""Cleanup ProductVariant: Remove suffix_code and supplier_sku

Revision ID: 240351b50747
Revises: ee78dd561c3a
Create Date: 2025-12-06 00:59:20.031675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240351b50747'
down_revision = 'ee78dd561c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=50),
               comment='SKU短码 (System Code), 如 101120501DWD',
               existing_comment='SKU短码, 如 127240081WB',
               existing_nullable=False)
        batch_op.alter_column('feature_code',
               existing_type=sa.VARCHAR(length=200),
               comment='SKU特征码 (Business Code), 如 HL-TOY-CAM-20-D-WB',
               existing_comment='SKU特征码, 如 ...-2P-CH-AM-WB',
               existing_nullable=True)
        batch_op.drop_column('suffix_code')
        batch_op.drop_column('supplier_sku')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_sku', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('suffix_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='生成短码用的后缀, 如 WB'))
        batch_op.alter_column('feature_code',
               existing_type=sa.VARCHAR(length=200),
               comment='SKU特征码, 如 ...-2P-CH-AM-WB',
               existing_comment='SKU特征码 (Business Code), 如 HL-TOY-CAM-20-D-WB',
               existing_nullable=True)
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=50),
               comment='SKU短码, 如 127240081WB',
               existing_comment='SKU短码 (System Code), 如 101120501DWD',
               existing_nullable=False)

    # ### end Alembic commands ###
