"""refactor_product_physical_properties

Revision ID: 26750682da6c
Revises: 6a93fd8ef740
Create Date: 2025-12-09 03:10:00.257151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26750682da6c'
down_revision = '6a93fd8ef740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_weight', sa.DECIMAL(precision=10, scale=3), nullable=True, comment='Net Weight (KG)'))
        batch_op.add_column(sa.Column('gross_weight', sa.DECIMAL(precision=10, scale=3), nullable=True, comment='Gross Weight (KG)'))
        batch_op.add_column(sa.Column('pack_length', sa.DECIMAL(precision=10, scale=1), nullable=True, comment='Package Length (CM)'))
        batch_op.add_column(sa.Column('pack_width', sa.DECIMAL(precision=10, scale=1), nullable=True, comment='Package Width (CM)'))
        batch_op.add_column(sa.Column('pack_height', sa.DECIMAL(precision=10, scale=1), nullable=True, comment='Package Height (CM)'))
        batch_op.drop_column('length')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')
        batch_op.drop_column('width')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Width in CM'))
        batch_op.add_column(sa.Column('height', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Height in CM'))
        batch_op.add_column(sa.Column('weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Weight in KG'))
        batch_op.add_column(sa.Column('length', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Length in CM'))
        batch_op.drop_column('pack_height')
        batch_op.drop_column('pack_width')
        batch_op.drop_column('pack_length')
        batch_op.drop_column('gross_weight')
        batch_op.drop_column('net_weight')

    # ### end Alembic commands ###
