"""add default_usage to category_attributes

Revision ID: 2c5c05733f58
Revises: 240351b50747
Create Date: 2025-12-06 13:49:12.508727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5c05733f58'
down_revision = '240351b50747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_attributes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_usage', sa.String(length=10), nullable=True, comment='默认用途: spu/sku'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_attributes', schema=None) as batch_op:
        batch_op.drop_column('default_usage')

    # ### end Alembic commands ###
