"""add_paid_amount_to_delivery_contract

Revision ID: 2f4bc2c3e5ca
Revises: 72c8670914c8
Create Date: 2025-11-27 14:00:14.586491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4bc2c3e5ca'
down_revision = '72c8670914c8'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Add column as nullable first
    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_amount', sa.DECIMAL(precision=18, scale=2), nullable=True))

    # 2. Fill existing rows with default value 0
    op.execute("UPDATE scm_delivery_contracts SET paid_amount = 0 WHERE paid_amount IS NULL")

    # 3. Alter column to be non-nullable
    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.alter_column('paid_amount', nullable=False, existing_type=sa.DECIMAL(precision=18, scale=2))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.drop_column('paid_amount')

    # ### end Alembic commands ###
