"""Add group_name to attribute_definitions and category_attributes

Revision ID: 3378631318c7
Revises: 06c8cbb567e8
Create Date: 2025-12-05 08:15:06.176243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3378631318c7'
down_revision = '06c8cbb567e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attribute_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.String(length=50), nullable=True, comment='属性分组名称'))

    with op.batch_alter_table('category_attributes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.String(length=50), nullable=True, comment='Override attribute group'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_attributes', schema=None) as batch_op:
        batch_op.drop_column('group_name')

    with op.batch_alter_table('attribute_definitions', schema=None) as batch_op:
        batch_op.drop_column('group_name')

    # ### end Alembic commands ###
