"""add_provider_code_to_third_party_services

Revision ID: 43c1ea6841c3
Revises: b2d1f29e6fa2
Create Date: 2025-12-11 04:56:56.286195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c1ea6841c3'
down_revision = 'b2d1f29e6fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('third_party_warehouse_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('remote_code', sa.String(length=50), nullable=False),
    sa.Column('remote_name', sa.String(length=100), nullable=False),
    sa.Column('local_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['local_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['third_party_services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'remote_code', name='uix_service_remote_wh')
    )
    with op.batch_alter_table('third_party_services', schema=None) as batch_op:
        # 先添加可为空的列
        batch_op.add_column(sa.Column('provider_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_sync_time', sa.DateTime(), nullable=True))
    
    # 为现有记录设置默认值
    op.execute("UPDATE third_party_services SET provider_code = '4px' WHERE provider_code IS NULL")
    op.execute("UPDATE third_party_services SET is_active = true WHERE is_active IS NULL")
    op.execute("UPDATE third_party_services SET status = 'unknown' WHERE status IS NULL")
    
    # 修改列为不可为空
    with op.batch_alter_table('third_party_services', schema=None) as batch_op:
        batch_op.alter_column('provider_code', nullable=False)
        batch_op.alter_column('is_active', nullable=False)
        batch_op.alter_column('status', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('third_party_services', schema=None) as batch_op:
        batch_op.drop_column('last_sync_time')
        batch_op.drop_column('status')
        batch_op.drop_column('is_active')
        batch_op.drop_column('provider_code')

    op.drop_table('third_party_warehouse_maps')
    # ### end Alembic commands ###
