"""add_mobile_field_to_users

Revision ID: 448a77c4d244
Revises: 17e4792b2e4d
Create Date: 2025-12-17 14:14:01.325827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '448a77c4d244'
down_revision = '17e4792b2e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declaration_audit_logs', schema=None) as batch_op:
        batch_op.alter_column('declaration_id',
               existing_type=sa.INTEGER(),
               comment='报关单ID',
               existing_nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=50),
               comment='操作类型: create/update/delete/status_change/file_upload',
               existing_nullable=False)
        batch_op.alter_column('action_description',
               existing_type=sa.VARCHAR(length=255),
               comment='操作描述',
               existing_nullable=False)
        batch_op.alter_column('old_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='变更前的值',
               existing_nullable=True)
        batch_op.alter_column('new_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='变更后的值',
               existing_nullable=True)
        batch_op.alter_column('changes_summary',
               existing_type=sa.TEXT(),
               comment='变更摘要',
               existing_nullable=True)
        batch_op.alter_column('operator_id',
               existing_type=sa.INTEGER(),
               comment='操作人ID',
               existing_nullable=True)
        batch_op.alter_column('operator_name',
               existing_type=sa.VARCHAR(length=100),
               comment='操作人姓名',
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=50),
               comment='IP地址',
               existing_nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=500),
               comment='用户代理',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_audit_action'))
        batch_op.drop_index(batch_op.f('idx_audit_created_at'))
        batch_op.drop_index(batch_op.f('idx_audit_declaration'))
        batch_op.drop_index(batch_op.f('idx_audit_operator'))
        batch_op.drop_constraint(batch_op.f('customs_declaration_audit_logs_declaration_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'customs_declarations', ['declaration_id'], ['id'])

    with op.batch_alter_table('customs_declaration_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_decl_items_declaration'))
        batch_op.drop_index(batch_op.f('idx_decl_items_hs_code'))
        batch_op.drop_index(batch_op.f('idx_decl_items_product'))
        batch_op.drop_index(batch_op.f('idx_decl_items_supplier'))

    with op.batch_alter_table('customs_declarations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_declarations_company'))
        batch_op.drop_index(batch_op.f('idx_declarations_created_at'))
        batch_op.drop_index(batch_op.f('idx_declarations_customs_no'))
        batch_op.drop_index(batch_op.f('idx_declarations_entry_no'))
        batch_op.drop_index(batch_op.f('idx_declarations_export_date'))
        batch_op.drop_index(batch_op.f('idx_declarations_pre_entry_no'))
        batch_op.drop_index(batch_op.f('idx_declarations_status'))
        batch_op.drop_index(batch_op.f('idx_declarations_status_company'))
        batch_op.drop_index(batch_op.f('idx_declarations_status_date'))

    with op.batch_alter_table('sys_companies', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=20),
               comment='公司代码(用于单据前缀)',
               existing_comment='公司代码(用于单据前缀，如：HR-YL-2412-0001)',
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mobile')

    with op.batch_alter_table('sys_companies', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=20),
               comment='公司代码(用于单据前缀，如：HR-YL-2412-0001)',
               existing_comment='公司代码(用于单据前缀)',
               existing_nullable=True)

    with op.batch_alter_table('customs_declarations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_declarations_status_date'), ['status', sa.literal_column('export_date DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_declarations_status_company'), ['status', 'internal_shipper_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_declarations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_declarations_pre_entry_no'), ['pre_entry_no'], unique=False)
        batch_op.create_index(batch_op.f('idx_declarations_export_date'), [sa.literal_column('export_date DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_declarations_entry_no'), ['entry_no'], unique=False)
        batch_op.create_index(batch_op.f('idx_declarations_customs_no'), ['customs_no'], unique=False)
        batch_op.create_index(batch_op.f('idx_declarations_created_at'), [sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_declarations_company'), ['internal_shipper_id'], unique=False)

    with op.batch_alter_table('customs_declaration_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_decl_items_supplier'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_decl_items_product'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_decl_items_hs_code'), ['hs_code'], unique=False)
        batch_op.create_index(batch_op.f('idx_decl_items_declaration'), ['declaration_id'], unique=False)

    with op.batch_alter_table('customs_declaration_audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('customs_declaration_audit_logs_declaration_id_fkey'), 'customs_declarations', ['declaration_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_audit_operator'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_declaration'), ['declaration_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_created_at'), [sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_action'), ['action'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='用户代理',
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='IP地址',
               existing_nullable=True)
        batch_op.alter_column('operator_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='操作人姓名',
               existing_nullable=True)
        batch_op.alter_column('operator_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='操作人ID',
               existing_nullable=True)
        batch_op.alter_column('changes_summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='变更摘要',
               existing_nullable=True)
        batch_op.alter_column('new_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='变更后的值',
               existing_nullable=True)
        batch_op.alter_column('old_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='变更前的值',
               existing_nullable=True)
        batch_op.alter_column('action_description',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='操作描述',
               existing_nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='操作类型: create/update/delete/status_change/file_upload',
               existing_nullable=False)
        batch_op.alter_column('declaration_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='报关单ID',
               existing_nullable=False)

    # ### end Alembic commands ###
