"""Add optimistic locking and contract change log

Revision ID: 47dea84e5d23
Revises: f21f83573982
Create Date: 2025-11-30 03:55:25.612791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47dea84e5d23'
down_revision = 'f21f83573982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scm_contract_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True, comment='操作人ID'),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('change_reason', sa.String(length=255), nullable=True),
    sa.Column('content_before', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['scm_delivery_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='0', comment='乐观锁版本号'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.drop_column('version')

    op.drop_table('scm_contract_change_logs')
    # ### end Alembic commands ###
