"""add notes to ScmDeliveryItem

Revision ID: 488504371f00
Revises: d818a0584eb8
Create Date: 2025-11-27 06:57:03.620008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488504371f00'
down_revision = 'd818a0584eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scm_delivery_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scm_delivery_items', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
