"""remove_entry_no_field

Revision ID: 498e17df12c6
Revises: f48b1719e2d2
Create Date: 2025-12-17 21:10:04.886273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498e17df12c6'
down_revision = 'f48b1719e2d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declarations', schema=None) as batch_op:
        batch_op.alter_column('pre_entry_no',
               existing_type=sa.VARCHAR(length=50),
               comment='预录入编号（主标识）',
               existing_comment='预录入编号',
               existing_nullable=True)
        batch_op.alter_column('customs_no',
               existing_type=sa.VARCHAR(length=50),
               comment='海关编号/报关单单号',
               existing_comment='海关编号',
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('customs_declarations_entry_no_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['pre_entry_no'])
        batch_op.drop_column('entry_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declarations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='系统内部编号'))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('customs_declarations_entry_no_key'), ['entry_no'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('customs_no',
               existing_type=sa.VARCHAR(length=50),
               comment='海关编号',
               existing_comment='海关编号/报关单单号',
               existing_nullable=True)
        batch_op.alter_column('pre_entry_no',
               existing_type=sa.VARCHAR(length=50),
               comment='预录入编号',
               existing_comment='预录入编号（主标识）',
               existing_nullable=True)

    # ### end Alembic commands ###
