"""add cbm field to customs_declaration_items

Revision ID: 49a7955f3095
Revises: 08cfb26ec24c
Create Date: 2025-12-18 01:19:35.172121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a7955f3095'
down_revision = '08cfb26ec24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declaration_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cbm', sa.DECIMAL(precision=10, scale=6), nullable=True, comment='体积(CBM)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declaration_items', schema=None) as batch_op:
        batch_op.drop_column('cbm')

    # ### end Alembic commands ###
