"""add_sync_fields_to_attachments_with_default

Revision ID: 4dc10e92afb2
Revises: 70350f311991
Create Date: 2025-12-16 05:04:50.070685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc10e92afb2'
down_revision = '70350f311991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customs_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('declaration_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='显示文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='NAS相对路径(含文件名)'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小(Bytes)'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='文件扩展名'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='目录分类'),
    sa.Column('slot_title', sa.String(length=100), nullable=True, comment='业务插槽标识'),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True, comment='上传人ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='synced', nullable=False, comment='状态: synced/missing'),
    sa.Column('source', sa.String(length=20), server_default='upload', nullable=False, comment='来源: upload/nas_sync'),
    sa.Column('sync_message', sa.String(length=255), nullable=True, comment='同步异常备注'),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True, comment='最后同步时间'),
    sa.ForeignKeyConstraint(['declaration_id'], ['customs_declarations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customs_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customs_attachments_declaration_id'), ['declaration_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customs_attachments_declaration_id'))

    op.drop_table('customs_attachments')
    # ### end Alembic commands ###
