"""完善发货单模型-添加税务和采购信息字段

Revision ID: 57c8a8a82ef3
Revises: e9af8e1a6e56
Create Date: 2025-12-18 06:24:32.236924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57c8a8a82ef3'
down_revision = 'e9af8e1a6e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='产品中文名称',
               existing_nullable=False)
        batch_op.drop_column('name_en')

    with op.batch_alter_table('shipment_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate', sa.DECIMAL(precision=5, scale=4), nullable=True, comment='税率(如0.13表示13%)'))
        batch_op.add_column(sa.Column('tax_amount', sa.DECIMAL(precision=18, scale=2), nullable=True, comment='税额'))
        batch_op.add_column(sa.Column('unit_price_with_tax', sa.DECIMAL(precision=18, scale=4), nullable=True, comment='含税单价'))
        batch_op.add_column(sa.Column('total_price_with_tax', sa.DECIMAL(precision=18, scale=2), nullable=True, comment='含税总价'))
        batch_op.add_column(sa.Column('purchase_order_id', sa.Integer(), nullable=True, comment='采购单ID'))
        batch_op.alter_column('unit_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='单价（不含税）',
               existing_comment='单价',
               existing_nullable=True)
        batch_op.alter_column('total_price',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='总价（不含税）',
               existing_comment='总价',
               existing_nullable=True)

    with op.batch_alter_table('shipment_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_tax_amount', sa.DECIMAL(precision=18, scale=2), nullable=True, comment='总税额'))
        batch_op.add_column(sa.Column('total_amount_with_tax', sa.DECIMAL(precision=18, scale=2), nullable=True, comment='含税总金额'))
        batch_op.alter_column('total_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='总金额（不含税）',
               existing_comment='总金额',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_orders', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='总金额',
               existing_comment='总金额（不含税）',
               existing_nullable=True)
        batch_op.drop_column('total_amount_with_tax')
        batch_op.drop_column('total_tax_amount')

    with op.batch_alter_table('shipment_order_items', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='总价',
               existing_comment='总价（不含税）',
               existing_nullable=True)
        batch_op.alter_column('unit_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='单价',
               existing_comment='单价（不含税）',
               existing_nullable=True)
        batch_op.drop_column('purchase_order_id')
        batch_op.drop_column('total_price_with_tax')
        batch_op.drop_column('unit_price_with_tax')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('tax_rate')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='产品英文名称'))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               comment='产品中文名称',
               existing_nullable=False)

    # ### end Alembic commands ###
