"""add delivery info

Revision ID: 57fa1a77cf8e
Revises: 3a3c62993d83
Create Date: 2025-11-27 15:02:23.844138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57fa1a77cf8e'
down_revision = '3a3c62993d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=255), nullable=True, comment='交付地点'))
        batch_op.add_column(sa.Column('delivery_date', sa.Date(), nullable=True, comment='送货日期'))
        batch_op.add_column(sa.Column('notes', sa.String(length=500), nullable=True, comment='合同备注'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('delivery_date')
        batch_op.drop_column('delivery_address')

    # ### end Alembic commands ###
