"""add qty_1 and unit_1 to customs_declaration_items

Revision ID: 5804495c05ba
Revises: fea4aae536ba
Create Date: 2025-12-16 13:26:00.841309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5804495c05ba'
down_revision = 'fea4aae536ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declaration_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qty_1', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='数量及单位1-法定数量'))
        batch_op.add_column(sa.Column('unit_1', sa.String(length=20), nullable=True, comment='数量及单位1-法定单位'))
        batch_op.alter_column('qty',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               comment='数量及单位1-数量 (成交数量)',
               existing_comment='数量及单位1-数量',
               existing_nullable=False)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=20),
               comment='数量及单位1-单位 (成交单位)',
               existing_comment='数量及单位1-单位',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declaration_items', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=20),
               comment='数量及单位1-单位',
               existing_comment='数量及单位1-单位 (成交单位)',
               existing_nullable=False)
        batch_op.alter_column('qty',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               comment='数量及单位1-数量',
               existing_comment='数量及单位1-数量 (成交数量)',
               existing_nullable=False)
        batch_op.drop_column('unit_1')
        batch_op.drop_column('qty_1')

    # ### end Alembic commands ###
