"""Update vehicle schema

Revision ID: 64e4dc83c6a9
Revises: f4ba8b42fb57
Create Date: 2025-11-21 08:28:41.575621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e4dc83c6a9'
down_revision = 'f4ba8b42fb57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('abbr', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('abbr')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
