"""rename CustomsItem to CustomsDeclarationItem

Revision ID: 673c1d719b26
Revises: e099913b18c7
Create Date: 2025-12-12 14:09:32.257027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '673c1d719b26'
down_revision = 'e099913b18c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create new table
    op.create_table('customs_declaration_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('declaration_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('item_no', sa.Integer(), nullable=False, comment='项号'),
    sa.Column('hs_code', sa.String(length=20), nullable=True, comment='商品编号'),
    sa.Column('product_name_spec', sa.Text(), nullable=True, comment='商品名称及规格型号'),
    sa.Column('qty', sa.DECIMAL(precision=12, scale=4), nullable=False, comment='数量及单位1-数量'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='数量及单位1-单位'),
    sa.Column('qty_2', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='数量及单位2-数量'),
    sa.Column('unit_2', sa.String(length=20), nullable=True, comment='数量及单位2-单位'),
    sa.Column('usd_unit_price', sa.DECIMAL(precision=18, scale=4), nullable=False, comment='单价'),
    sa.Column('usd_total', sa.DECIMAL(precision=18, scale=2), nullable=False, comment='总价'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='币制'),
    sa.Column('origin_country', sa.String(length=50), nullable=True, comment='原产国(地区)'),
    sa.Column('final_dest_country', sa.String(length=50), nullable=True, comment='最终目的国(地区)'),
    sa.Column('district_code', sa.String(length=20), nullable=True, comment='境内货源地'),
    sa.Column('exemption_way', sa.String(length=20), nullable=True, comment='征免'),
    sa.Column('supplier_id', sa.Integer(), nullable=True, comment='供应商ID'),
    sa.Column('sku', sa.String(length=100), nullable=True, comment='SKU编码(冗余)'),
    sa.Column('box_no', sa.String(length=50), nullable=True, comment='箱号'),
    sa.Column('net_weight', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='净重(KG)'),
    sa.Column('gross_weight', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='毛重(KG)'),
    sa.Column('rma_exchange_cost', sa.DECIMAL(precision=10, scale=4), nullable=True),
    # Add potentially missing columns from user's manual edits if any (e.g. declaration_elements)
    # Based on previous context, user was advised to add declaration_elements, but it might not be in the model definition I just read.
    # I will assume the model definition I read is the source of truth.
    
    sa.ForeignKeyConstraint(['declaration_id'], ['customs_declarations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['sys_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # 2. Drop constraints on OLD table
    with op.batch_alter_table('tax_refund_matches', schema=None) as batch_op:
        batch_op.drop_constraint('tax_refund_matches_customs_item_id_fkey', type_='foreignkey')

    # 3. Drop OLD table
    op.drop_table('customs_items')
    
    # 4. Add constraints to NEW table
    with op.batch_alter_table('tax_refund_matches', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'customs_declaration_items', ['customs_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_refund_matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tax_refund_matches_customs_item_id_fkey', 'customs_items', ['customs_item_id'], ['id'])

    op.create_table('customs_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('declaration_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_no', sa.INTEGER(), autoincrement=False, nullable=False, comment='项号'),
    sa.Column('hs_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='商品编号'),
    sa.Column('product_name_spec', sa.TEXT(), autoincrement=False, nullable=True, comment='商品名称及规格型号'),
    sa.Column('qty', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False, comment='数量及单位1-数量'),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='数量及单位1-单位'),
    sa.Column('qty_2', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True, comment='数量及单位2-数量'),
    sa.Column('unit_2', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='数量及单位2-单位'),
    sa.Column('usd_unit_price', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False, comment='单价'),
    sa.Column('usd_total', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False, comment='总价'),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False, comment='币制'),
    sa.Column('origin_country', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='原产国(地区)'),
    sa.Column('final_dest_country', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='最终目的国(地区)'),
    sa.Column('district_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='境内货源地'),
    sa.Column('exemption_way', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='征免'),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='供应商ID'),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='SKU编码(冗余)'),
    sa.Column('box_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='箱号'),
    sa.Column('net_weight', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True, comment='净重(KG)'),
    sa.Column('gross_weight', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True, comment='毛重(KG)'),
    sa.Column('rma_exchange_cost', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['declaration_id'], ['customs_declarations.id'], name='customs_items_declaration_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='customs_items_product_id_fkey'),
    sa.ForeignKeyConstraint(['supplier_id'], ['sys_suppliers.id'], name='customs_items_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customs_items_pkey')
    )
    op.drop_table('customs_declaration_items')
    # ### end Alembic commands ###
