"""Rename vehicles table to vehicle_aux

Revision ID: 67d05bed8a2e
Revises: 64e4dc83c6a9
Create Date: 2025-11-21 14:02:53.229227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d05bed8a2e'
down_revision = '64e4dc83c6a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop the foreign key constraint first
    with op.batch_alter_table('product_fitments', schema=None) as batch_op:
        batch_op.drop_constraint('product_fitments_vehicle_id_fkey', type_='foreignkey')
        
    # 2. Rename the table (preserves data) instead of create/drop
    op.rename_table('vehicles', 'vehicle_aux')
    
    # 3. Update the self-referencing foreign key on the new table
    with op.batch_alter_table('vehicle_aux', schema=None) as batch_op:
         batch_op.drop_constraint('vehicles_parent_id_fkey', type_='foreignkey')
         batch_op.create_foreign_key(None, 'vehicle_aux', ['parent_id'], ['id'])

    # 4. Re-create the foreign key on product_fitments pointing to the new table
    with op.batch_alter_table('product_fitments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'vehicle_aux', ['vehicle_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop FK
    with op.batch_alter_table('product_fitments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # 2. Rename back
    op.rename_table('vehicle_aux', 'vehicles')

    # 3. Fix self-referencing FK
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
         batch_op.drop_constraint(None, type_='foreignkey')
         batch_op.create_foreign_key('vehicles_parent_id_fkey', 'vehicles', ['parent_id'], ['id'])

    # 4. Restore FK
    with op.batch_alter_table('product_fitments', schema=None) as batch_op:
        batch_op.create_foreign_key('product_fitments_vehicle_id_fkey', 'vehicles', ['vehicle_id'], ['id'])

    # ### end Alembic commands ###
