"""category_attributes table default_usage change to  attribute_scope

Revision ID: 6a93fd8ef740
Revises: 2c5c05733f58
Create Date: 2025-12-06 14:37:54.426489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a93fd8ef740'
down_revision = '2c5c05733f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_attributes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attribute_scope', sa.String(length=10), nullable=True, comment='属性作用域: spu/sku'))
        batch_op.drop_column('default_usage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_attributes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_usage', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='默认用途: spu/sku'))
        batch_op.drop_column('attribute_scope')

    # ### end Alembic commands ###
