"""Add data permission tables

Revision ID: 6cf03e4b387c
Revises: 176400d0881c
Create Date: 2025-11-23 04:36:54.332447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf03e4b387c'
down_revision = '176400d0881c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_permission_metas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_permission_metas_key'))
        batch_op.create_unique_constraint(None, ['key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_permission_metas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_data_permission_metas_key'), ['key'], unique=True)

    # ### end Alembic commands ###
