"""Add warehouse models

Revision ID: 722e2ca5176b
Revises: 81858438e615
Create Date: 2025-12-10 06:50:24.180362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '722e2ca5176b'
down_revision = '81858438e615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_product_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('location_type', sa.String(length=20), nullable=False),
    sa.Column('ownership_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('business_type', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('api_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('child_warehouse_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('capacity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_volume', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('stock_allocation_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('virtual_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('source_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_product_group_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.Column('fixed_amount', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('policy_mode', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['virtual_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['warehouse_product_group_id'], ['warehouse_product_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_allocation_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_allocation_policies_virtual_warehouse_id'), ['virtual_warehouse_id'], unique=False)

    op.create_table('stock_discrepancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('local_qty', sa.Integer(), nullable=False),
    sa.Column('remote_qty', sa.Integer(), nullable=False),
    sa.Column('diff_ratio', sa.Float(), nullable=True),
    sa.Column('diff_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolver_id', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('physical_quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('allocated_quantity', sa.Integer(), nullable=False),
    sa.Column('in_transit_quantity', sa.Integer(), nullable=False),
    sa.Column('damaged_quantity', sa.Integer(), nullable=False),
    sa.Column('batch_no', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocks_sku'), ['sku'], unique=False)

    op.create_table('warehouse_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('allow_mixing', sa.Boolean(), nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('max_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_volume', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warehouse_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_locations_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('warehouse_product_group_items',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['warehouse_product_groups.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'sku')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(length=30), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('biz_time', sa.DateTime(), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('batch_no', sa.String(length=50), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_locations.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_order_no'), ['order_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_sku'), ['sku'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_sku'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_order_no'))

    op.drop_table('stock_movements')
    op.drop_table('warehouse_product_group_items')
    with op.batch_alter_table('warehouse_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_locations_warehouse_id'))

    op.drop_table('warehouse_locations')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_sku'))

    op.drop_table('stocks')
    op.drop_table('stock_discrepancies')
    with op.batch_alter_table('stock_allocation_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_allocation_policies_virtual_warehouse_id'))

    op.drop_table('stock_allocation_policies')
    op.drop_table('warehouses')
    op.drop_table('warehouse_product_groups')
    # ### end Alembic commands ###
