"""Rename ScmDeliveryItem to ScmDeliveryContractItem

Revision ID: 72c8670914c8
Revises: 488504371f00
Create Date: 2025-11-27 10:02:37.304778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c8670914c8'
down_revision = '488504371f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scm_delivery_contract_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('l1_contract_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('confirmed_qty', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('total_price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['l1_contract_id'], ['scm_delivery_contracts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('scm_delivery_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scm_delivery_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('l1_contract_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confirmed_qty', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['l1_contract_id'], ['scm_delivery_contracts.id'], name=op.f('scm_delivery_items_l1_contract_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('scm_delivery_items_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('scm_delivery_items_pkey'))
    )
    op.drop_table('scm_delivery_contract_items')
    # ### end Alembic commands ###
