"""Initial migration clean slate

Revision ID: 763e1e8a803e
Revises: 
Create Date: 2025-12-04 13:50:17.044182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '763e1e8a803e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('code_weight', sa.Integer(), nullable=False, comment='生成SKU特征码时的排序权重'),
    sa.Column('include_in_code', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_name')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('abbreviation', sa.String(length=10), nullable=True, comment='类目缩写,如 HL'),
    sa.Column('business_type', sa.String(length=20), nullable=False, comment='业务线类型'),
    sa.Column('spu_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='SPU表单配置与生成模板'),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('is_leaf', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('data_permission_metas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['data_permission_metas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('field_permission_metas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_key')
    )
    op.create_table('fin_bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trans_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('counterparty_name', sa.String(length=200), nullable=True),
    sa.Column('counterparty_account', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True, comment='银行流水号'),
    sa.Column('reconciled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fin_payment_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_no', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('beneficiary_name', sa.String(length=200), nullable=False),
    sa.Column('beneficiary_account', sa.String(length=100), nullable=False),
    sa.Column('beneficiary_bank', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_no')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_business_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False, comment='业务类型代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='规则名称'),
    sa.Column('generate_strategy', sa.String(length=50), nullable=False, comment='编码生成策略: vehicle/general/custom'),
    sa.Column('sku_prefix', sa.String(length=10), nullable=True, comment='SKU前缀'),
    sa.Column('requires_audit', sa.Boolean(), nullable=False, comment='创建产品是否需要审核'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='其他扩展配置'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_type')
    )
    op.create_table('product_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=False, comment='SPU缩写 (CHE, SIL)'),
    sa.Column('code', sa.String(length=50), nullable=True, comment='标准编码/ID'),
    sa.Column('level_type', sa.String(length=20), nullable=False, comment='brand, model, year'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['product_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_vehicles_abbreviation'), ['abbreviation'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_vehicles_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_vehicles_parent_id'), ['parent_id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sku_suffixes',
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('meaning_en', sa.String(length=50), nullable=True),
    sa.Column('meaning_cn', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('sys_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False, comment='法定名称'),
    sa.Column('short_name', sa.String(length=100), nullable=True, comment='简称'),
    sa.Column('code', sa.String(length=20), nullable=True, comment='公司代码(用于单据前缀)'),
    sa.Column('english_name', sa.String(length=200), nullable=True, comment='英文名称'),
    sa.Column('company_type', sa.String(length=50), nullable=True, comment='公司类型'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('unified_social_credit_code', sa.String(length=18), nullable=True, comment='统一社会信用代码'),
    sa.Column('tax_id', sa.String(length=50), nullable=True, comment='纳税人识别号'),
    sa.Column('business_license_no', sa.String(length=50), nullable=True, comment='营业执照注册号'),
    sa.Column('business_license_issue_date', sa.Date(), nullable=True, comment='营业执照发证日期'),
    sa.Column('business_license_expiry_date', sa.Date(), nullable=True, comment='营业执照有效期'),
    sa.Column('business_scope', sa.Text(), nullable=True, comment='经营范围'),
    sa.Column('registered_address', sa.String(length=500), nullable=True, comment='注册地址'),
    sa.Column('business_address', sa.String(length=500), nullable=True, comment='经营地址'),
    sa.Column('postal_code', sa.String(length=20), nullable=True, comment='邮政编码'),
    sa.Column('contact_person', sa.String(length=50), nullable=True, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=50), nullable=True, comment='联系电话'),
    sa.Column('contact_email', sa.String(length=100), nullable=True, comment='联系邮箱'),
    sa.Column('fax', sa.String(length=50), nullable=True, comment='传真'),
    sa.Column('bank_accounts', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='银行账户列表'),
    sa.Column('tax_rate', sa.Float(), nullable=True, comment='增值税率'),
    sa.Column('tax_registration_date', sa.Date(), nullable=True, comment='税务登记日期'),
    sa.Column('customs_code', sa.String(length=20), nullable=True, comment='海关编码'),
    sa.Column('customs_registration_no', sa.String(length=50), nullable=True, comment='海关注册登记编号'),
    sa.Column('inspection_code', sa.String(length=20), nullable=True, comment='检验检疫代码'),
    sa.Column('foreign_trade_operator_code', sa.String(length=50), nullable=True, comment='对外贸易经营者备案号'),
    sa.Column('forex_account', sa.String(length=100), nullable=True, comment='外汇账户'),
    sa.Column('forex_registration_no', sa.String(length=50), nullable=True, comment='外汇登记证号'),
    sa.Column('import_export_license_no', sa.String(length=50), nullable=True, comment='进出口许可证号'),
    sa.Column('import_export_license_expiry', sa.Date(), nullable=True, comment='进出口许可证有效期'),
    sa.Column('special_licenses', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='特殊资质列表'),
    sa.Column('default_currency', sa.String(length=10), nullable=True, comment='默认币种'),
    sa.Column('default_payment_term', sa.String(length=50), nullable=True, comment='默认付款条款'),
    sa.Column('credit_limit', sa.DECIMAL(precision=15, scale=2), nullable=True, comment='信用额度'),
    sa.Column('settlement_cycle', sa.Integer(), nullable=True, comment='结算周期（天）'),
    sa.Column('cross_border_platform_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='跨境平台账号'),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='附件列表'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('unified_social_credit_code')
    )
    op.create_table('sys_dictionaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True, comment='业务分类'),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('value_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sys_exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('safe_min', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('safe_max', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency')
    )
    op.create_table('sys_hs_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('refund_rate', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sys_payment_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='条款代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='条款名称'),
    sa.Column('baseline', sa.String(length=20), nullable=False, comment='基准日期'),
    sa.Column('days_offset', sa.Integer(), nullable=False, comment='偏移天数'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sys_tax_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sys_tax_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sys_tax_categories_code'), ['code'], unique=True)

    op.create_table('tax_customs_declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_no', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('export_date', sa.Date(), nullable=True),
    sa.Column('destination_country', sa.String(length=100), nullable=True),
    sa.Column('fob_total', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('exchange_rate', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_no')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('vehicle_aux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('abbr', sa.String(length=10), nullable=True),
    sa.Column('level_type', sa.String(length=20), nullable=True),
    sa.Column('full_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['vehicle_aux.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_attributes',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('include_in_code', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute_definitions.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'attribute_id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spu_code', sa.String(length=100), nullable=False, comment='SPU特征码, 如 HL-CHE-SIL-07-13'),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('spu_coding_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='生成SPU码所用的元数据'),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('main_image', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True, comment='Brand name if applicable'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_spu_code'), ['spu_code'], unique=True)

    op.create_table('role_data_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('category_key', sa.String(length=100), nullable=False),
    sa.Column('target_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resource_scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_data_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_data_permissions_role_id'), ['role_id'], unique=False)

    op.create_table('role_field_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_field_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_field_permissions_role_id'), ['role_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('sku_suffix_categories',
    sa.Column('sku_suffix_code', sa.String(length=5), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['sku_suffix_code'], ['sku_suffixes.code'], ),
    sa.PrimaryKeyConstraint('sku_suffix_code', 'category_id')
    )
    op.create_table('sys_dictionary_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dict_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['dict_id'], ['sys_dictionaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='供应商代码'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='供应商名称'),
    sa.Column('short_name', sa.String(length=100), nullable=True, comment='简称'),
    sa.Column('supplier_type', sa.String(length=50), nullable=False, comment='类型'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('grade', sa.String(length=10), nullable=True, comment='等级'),
    sa.Column('country', sa.String(length=50), nullable=True, comment='国家/地区'),
    sa.Column('province', sa.String(length=50), nullable=True, comment='省份'),
    sa.Column('city', sa.String(length=50), nullable=True, comment='城市'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='详细地址'),
    sa.Column('website', sa.String(length=200), nullable=True, comment='官网'),
    sa.Column('primary_contact', sa.String(length=50), nullable=True, comment='首要联系人'),
    sa.Column('primary_phone', sa.String(length=50), nullable=True, comment='联系电话'),
    sa.Column('primary_email', sa.String(length=100), nullable=True, comment='Email'),
    sa.Column('contacts', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='联系人列表'),
    sa.Column('tax_id', sa.String(length=50), nullable=True, comment='税号/VAT号'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='默认结算币种'),
    sa.Column('payment_term_id', sa.Integer(), nullable=True, comment='默认付款条款ID'),
    sa.Column('payment_terms', sa.String(length=100), nullable=True, comment='付款条款(旧字段/快照)'),
    sa.Column('payment_method', sa.String(length=50), nullable=True, comment='付款方式'),
    sa.Column('taxpayer_type', sa.String(length=20), nullable=True, comment='纳税人类型: general(一般), small(小规模)'),
    sa.Column('default_vat_rate', sa.Numeric(precision=5, scale=4), nullable=True, comment='默认开票税率'),
    sa.Column('bank_accounts', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='银行账户'),
    sa.Column('lead_time_days', sa.Integer(), nullable=True, comment='平均交货天数'),
    sa.Column('moq', sa.String(length=50), nullable=True, comment='最小起订量描述'),
    sa.Column('purchase_uid', sa.Integer(), nullable=True, comment='负责采购员ID'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='标签'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_term_id'], ['sys_payment_terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('fin_purchase_soas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soa_no', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('total_payable', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('invoice_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['sys_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('soa_no')
    )
    op.create_table('product_fitments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('sub_model', sa.String(length=50), nullable=True),
    sa.Column('year_start', sa.Integer(), nullable=True),
    sa.Column('year_end', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('fitment_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle_aux.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_fitments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_fitments_product_id'), ['product_id'], unique=False)

    op.create_table('product_reference_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('code_type', sa.String(length=20), nullable=False, comment='OE, OEM, PARTSLINK, HOLLANDER'),
    sa.Column('brand', sa.String(length=50), nullable=True, comment='Brand of the code e.g. Toyota, Bosch'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_reference_codes', schema=None) as batch_op:
        batch_op.create_index('idx_ref_code_lookup', ['code', 'code_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_reference_codes_code'), ['code'], unique=False)

    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False, comment='SKU短码, 如 127240081WB'),
    sa.Column('feature_code', sa.String(length=200), nullable=True, comment='SKU特征码, 如 ...-2P-CH-AM-WB'),
    sa.Column('suffix_code', sa.String(length=20), nullable=True, comment='生成短码用的后缀, 如 WB'),
    sa.Column('supplier_sku', sa.String(length=50), nullable=True),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Variant specific specs e.g. {color: red}'),
    sa.Column('quality_type', sa.String(length=20), nullable=False, comment='OEM, Aftermarket, Refurbished'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=True, comment='EAN/UPC'),
    sa.Column('image', sa.String(length=255), nullable=True, comment='Variant specific image'),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cost_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('weight', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Weight in KG'),
    sa.Column('length', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Length in CM'),
    sa.Column('width', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Width in CM'),
    sa.Column('height', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Height in CM'),
    sa.Column('hs_code_id', sa.Integer(), nullable=True),
    sa.Column('declared_name', sa.String(length=200), nullable=True),
    sa.Column('declared_unit', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hs_code_id'], ['sys_hs_codes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variants_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variants_feature_code'), ['feature_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variants_sku'), ['sku'], unique=True)

    op.create_table('scm_source_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_no', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('tracking_source', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['sys_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_no')
    )
    op.create_table('tax_customs_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('declaration_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('usd_unit_price', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('usd_total', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('rma_exchange_cost', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['declaration_id'], ['tax_customs_declarations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fin_payment_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soa_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True, comment='预计付款日'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='优先级 0-100'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['soa_id'], ['fin_purchase_soas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fin_payment_reconciles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('soa_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['soa_id'], ['fin_purchase_soas.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['fin_bank_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scm_delivery_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_no', sa.String(length=50), nullable=False),
    sa.Column('source_doc_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('delivery_address', sa.String(length=255), nullable=True, comment='交付地点'),
    sa.Column('delivery_date', sa.Date(), nullable=True, comment='送货日期'),
    sa.Column('notes', sa.String(length=500), nullable=True, comment='合同备注'),
    sa.Column('supplier_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='供应商快照'),
    sa.Column('payment_term_id', sa.Integer(), nullable=True, comment='付款条款ID'),
    sa.Column('payment_terms', sa.String(length=100), nullable=True, comment='付款条款(快照)'),
    sa.Column('payment_method', sa.String(length=50), nullable=True, comment='付款方式'),
    sa.Column('version', sa.Integer(), nullable=False, comment='乐观锁版本号'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['sys_companies.id'], ),
    sa.ForeignKeyConstraint(['payment_term_id'], ['sys_payment_terms.id'], ),
    sa.ForeignKeyConstraint(['source_doc_id'], ['scm_source_docs.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['sys_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_no')
    )
    op.create_table('tax_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_code', sa.String(length=50), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('amount_total', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('soa_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['soa_id'], ['fin_purchase_soas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_table('fin_purchase_soa_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soa_id', sa.Integer(), nullable=False),
    sa.Column('l1_contract_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False, comment='本期对账金额'),
    sa.ForeignKeyConstraint(['l1_contract_id'], ['scm_delivery_contracts.id'], ),
    sa.ForeignKeyConstraint(['soa_id'], ['fin_purchase_soas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fin_supply_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('l1_contract_id', sa.Integer(), nullable=False),
    sa.Column('contract_no', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reconciled_amount', sa.DECIMAL(precision=18, scale=2), nullable=False, comment='已纳入对账单金额'),
    sa.Column('paid_amount', sa.DECIMAL(precision=18, scale=2), nullable=False, comment='实付金额'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['l1_contract_id'], ['scm_delivery_contracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('l1_contract_id')
    )
    with op.batch_alter_table('fin_supply_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fin_supply_contracts_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('scm_contract_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True, comment='操作人ID'),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('change_reason', sa.String(length=255), nullable=True),
    sa.Column('content_before', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['scm_delivery_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scm_delivery_contract_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('l1_contract_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('confirmed_qty', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('total_price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['l1_contract_id'], ['scm_delivery_contracts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['tax_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fin_supply_contract_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_contract_id', sa.Integer(), nullable=False),
    sa.Column('invoice_name', sa.String(length=200), nullable=False, comment='开票品名'),
    sa.Column('invoice_unit', sa.String(length=20), nullable=False, comment='开票单位'),
    sa.Column('specs', sa.String(length=200), nullable=True, comment='规格型号'),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=4), nullable=False, comment='聚合数量'),
    sa.Column('price_unit', sa.DECIMAL(precision=18, scale=4), nullable=False, comment='含税单价'),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False, comment='行总价'),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=False, comment='进项税率'),
    sa.Column('tax_code', sa.String(length=50), nullable=False, comment='税收分类编码'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supply_contract_id'], ['fin_supply_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_refund_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customs_item_id', sa.Integer(), nullable=False),
    sa.Column('invoice_item_id', sa.Integer(), nullable=False),
    sa.Column('matched_qty', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customs_item_id'], ['tax_customs_items.id'], ),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['tax_invoice_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_refund_matches')
    op.drop_table('fin_supply_contract_items')
    op.drop_table('tax_invoice_items')
    op.drop_table('scm_delivery_contract_items')
    op.drop_table('scm_contract_change_logs')
    with op.batch_alter_table('fin_supply_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fin_supply_contracts_supplier_id'))

    op.drop_table('fin_supply_contracts')
    op.drop_table('fin_purchase_soa_details')
    op.drop_table('tax_invoices')
    op.drop_table('scm_delivery_contracts')
    op.drop_table('fin_payment_reconciles')
    op.drop_table('fin_payment_pool')
    op.drop_table('tax_customs_items')
    op.drop_table('scm_source_docs')
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variants_sku'))
        batch_op.drop_index(batch_op.f('ix_product_variants_feature_code'))
        batch_op.drop_index(batch_op.f('ix_product_variants_barcode'))

    op.drop_table('product_variants')
    with op.batch_alter_table('product_reference_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_reference_codes_code'))
        batch_op.drop_index('idx_ref_code_lookup')

    op.drop_table('product_reference_codes')
    with op.batch_alter_table('product_fitments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_fitments_product_id'))

    op.drop_table('product_fitments')
    op.drop_table('fin_purchase_soas')
    op.drop_table('user_roles')
    op.drop_table('sys_suppliers')
    op.drop_table('sys_dictionary_items')
    op.drop_table('sku_suffix_categories')
    op.drop_table('role_permissions')
    with op.batch_alter_table('role_field_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_field_permissions_role_id'))

    op.drop_table('role_field_permissions')
    with op.batch_alter_table('role_data_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_data_permissions_role_id'))

    op.drop_table('role_data_permissions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_spu_code'))

    op.drop_table('products')
    op.drop_table('category_attributes')
    op.drop_table('vehicle_aux')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('tax_customs_declarations')
    with op.batch_alter_table('sys_tax_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sys_tax_categories_code'))

    op.drop_table('sys_tax_categories')
    op.drop_table('sys_payment_terms')
    op.drop_table('sys_hs_codes')
    op.drop_table('sys_exchange_rates')
    op.drop_table('sys_dictionaries')
    op.drop_table('sys_companies')
    op.drop_table('sku_suffixes')
    op.drop_table('roles')
    with op.batch_alter_table('product_vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_vehicles_parent_id'))
        batch_op.drop_index(batch_op.f('ix_product_vehicles_code'))
        batch_op.drop_index(batch_op.f('ix_product_vehicles_abbreviation'))

    op.drop_table('product_vehicles')
    op.drop_table('product_business_rules')
    op.drop_table('permissions')
    op.drop_table('fin_payment_requests')
    op.drop_table('fin_bank_transactions')
    op.drop_table('field_permission_metas')
    op.drop_table('data_permission_metas')
    op.drop_table('categories')
    op.drop_table('attribute_definitions')
    # ### end Alembic commands ###
