"""add overseas consignee

Revision ID: 7e1b6cf76e4c
Revises: a7e668414799
Create Date: 2025-12-17 07:31:58.213054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1b6cf76e4c'
down_revision = 'a7e668414799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customs_overseas_consignees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='收货人名称'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='地址'),
    sa.Column('contact_info', sa.String(length=200), nullable=True, comment='联系方式'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='国家/地区'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customs_overseas_consignees')
    # ### end Alembic commands ###
