"""Update vehicle level types

Revision ID: 7f96a36fba92
Revises: 144bc9ebfd67
Create Date: 2025-12-05 00:45:48.754413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f96a36fba92'
down_revision = '144bc9ebfd67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_vehicles', schema=None) as batch_op:
        batch_op.alter_column('level_type',
               existing_type=sa.VARCHAR(length=20),
               comment='make, model, year',
               existing_comment='brand, model, year',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_vehicles', schema=None) as batch_op:
        batch_op.alter_column('level_type',
               existing_type=sa.VARCHAR(length=20),
               comment='brand, model, year',
               existing_comment='make, model, year',
               existing_nullable=False)

    # ### end Alembic commands ###
