"""add_shipment_supply_invoice_tables

Revision ID: 80619c8bee36
Revises: 1242638ab8f0
Create Date: 2025-12-17 15:36:47.568591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80619c8bee36'
down_revision = '1242638ab8f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_no', sa.String(length=50), nullable=False, comment='发货单号（唯一）'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='来源'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('external_order_no', sa.String(length=100), nullable=True, comment='外部订单号(领星/易仓)'),
    sa.Column('external_tracking_no', sa.String(length=100), nullable=True, comment='外部跟踪号'),
    sa.Column('external_source_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='原始数据快照'),
    sa.Column('shipper_company_id', sa.Integer(), nullable=False, comment='发货公司'),
    sa.Column('consignee_id', sa.Integer(), nullable=True, comment='境外收货人'),
    sa.Column('consignee_name', sa.String(length=255), nullable=True, comment='收货人名称'),
    sa.Column('consignee_address', sa.Text(), nullable=True, comment='收货地址'),
    sa.Column('consignee_country', sa.String(length=100), nullable=True, comment='收货国家'),
    sa.Column('logistics_provider', sa.String(length=100), nullable=True, comment='物流商'),
    sa.Column('tracking_no', sa.String(length=100), nullable=True, comment='物流跟踪号'),
    sa.Column('shipping_method', sa.String(length=50), nullable=True, comment='运输方式(海运/空运/快递)'),
    sa.Column('estimated_ship_date', sa.Date(), nullable=True, comment='预计发货日期'),
    sa.Column('actual_ship_date', sa.Date(), nullable=True, comment='实际发货日期'),
    sa.Column('total_packages', sa.Integer(), nullable=True, comment='总件数'),
    sa.Column('total_gross_weight', sa.DECIMAL(precision=18, scale=4), nullable=True, comment='总毛重(kg)'),
    sa.Column('total_net_weight', sa.DECIMAL(precision=18, scale=4), nullable=True, comment='总净重(kg)'),
    sa.Column('total_volume', sa.DECIMAL(precision=18, scale=4), nullable=True, comment='总体积(m³)'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='币种'),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=True, comment='总金额'),
    sa.Column('customs_declaration_id', sa.Integer(), nullable=True, comment='关联报关单'),
    sa.Column('is_declared', sa.Boolean(), nullable=False, comment='是否已生成报关单'),
    sa.Column('is_contracted', sa.Boolean(), nullable=False, comment='是否已生成交付合同'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True, comment='最后同步时间'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='同步错误信息'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['consignee_id'], ['customs_overseas_consignees.id'], ),
    sa.ForeignKeyConstraint(['customs_declaration_id'], ['customs_declarations.id'], ),
    sa.ForeignKeyConstraint(['shipper_company_id'], ['sys_companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_no')
    )
    op.create_table('shipment_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True, comment='系统产品ID'),
    sa.Column('sku', sa.String(length=100), nullable=False, comment='SKU'),
    sa.Column('product_name', sa.String(length=255), nullable=False, comment='商品名称'),
    sa.Column('product_name_en', sa.String(length=255), nullable=True, comment='英文品名'),
    sa.Column('hs_code', sa.String(length=20), nullable=True, comment='HS编码'),
    sa.Column('customs_product_id', sa.Integer(), nullable=True, comment='归类商品ID'),
    sa.Column('quantity', sa.DECIMAL(precision=12, scale=4), nullable=False, comment='数量'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='单位'),
    sa.Column('unit_price', sa.DECIMAL(precision=18, scale=4), nullable=True, comment='单价'),
    sa.Column('total_price', sa.DECIMAL(precision=18, scale=2), nullable=True, comment='总价'),
    sa.Column('unit_weight', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='单件重量(kg)'),
    sa.Column('total_weight', sa.DECIMAL(precision=18, scale=4), nullable=True, comment='总重量(kg)'),
    sa.Column('origin_country', sa.String(length=100), nullable=True, comment='原产国'),
    sa.Column('external_item_id', sa.String(length=100), nullable=True, comment='外部商品ID'),
    sa.Column('supplier_id', sa.Integer(), nullable=True, comment='供应商ID'),
    sa.ForeignKeyConstraint(['customs_product_id'], ['customs_products.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['sys_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scm_supply_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_no', sa.String(length=50), nullable=False, comment='开票合同号（唯一）'),
    sa.Column('delivery_contract_id', sa.Integer(), nullable=False, comment='主交付合同ID（1对1唯一）'),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False, comment='总金额（不含税）'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='币种'),
    sa.Column('tax_rate', sa.DECIMAL(precision=5, scale=4), nullable=False, comment='税率(如0.13)'),
    sa.Column('total_amount_with_tax', sa.DECIMAL(precision=18, scale=2), nullable=False, comment='含税总额'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='合同状态'),
    sa.Column('invoice_status', sa.String(length=20), nullable=False, comment='开票状态: uninvoiced/partial/invoiced'),
    sa.Column('invoiced_amount', sa.DECIMAL(precision=18, scale=2), nullable=False, comment='已开票金额'),
    sa.Column('notes', sa.Text(), nullable=True, comment='开票说明'),
    sa.Column('contract_date', sa.Date(), nullable=False, comment='合同日期'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['delivery_contract_id'], ['scm_delivery_contracts.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['sys_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_no'),
    sa.UniqueConstraint('delivery_contract_id', name='uk_delivery_contract_id')
    )
    op.create_table('scm_supply_contract_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False, comment='开票商品名称'),
    sa.Column('specification', sa.String(length=255), nullable=True, comment='规格型号'),
    sa.Column('quantity', sa.DECIMAL(precision=12, scale=4), nullable=False, comment='数量'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='开票单位(台/套/箱)'),
    sa.Column('unit_price', sa.DECIMAL(precision=18, scale=4), nullable=False, comment='单价（不含税）'),
    sa.Column('total_price', sa.DECIMAL(precision=18, scale=2), nullable=False, comment='小计（不含税）'),
    sa.Column('tax_amount', sa.DECIMAL(precision=18, scale=2), nullable=False, comment='税额'),
    sa.Column('source_delivery_item_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='源交付合同明细ID列表(用于溯源)'),
    sa.ForeignKeyConstraint(['contract_id'], ['scm_supply_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_tax_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False, comment='发票号码（唯一）'),
    sa.Column('invoice_code', sa.String(length=50), nullable=False, comment='发票代码'),
    sa.Column('supply_contract_id', sa.Integer(), nullable=False, comment='关联开票合同'),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False, comment='不含税金额'),
    sa.Column('tax_amount', sa.DECIMAL(precision=18, scale=2), nullable=False, comment='税额'),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False, comment='价税合计'),
    sa.Column('invoice_type', sa.String(length=20), nullable=False, comment='special/ordinary/electronic'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='valid/cancelled/invalid'),
    sa.Column('invoice_date', sa.Date(), nullable=False, comment='开票日期'),
    sa.Column('received_date', sa.Date(), nullable=True, comment='收票日期'),
    sa.Column('attachment_url', sa.String(length=255), nullable=True, comment='发票扫描件'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['supplier_id'], ['sys_suppliers.id'], ),
    sa.ForeignKeyConstraint(['supply_contract_id'], ['scm_supply_contracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    with op.batch_alter_table('customs_declarations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipment_id', sa.Integer(), nullable=True, comment='关联发货单'))
        batch_op.create_foreign_key(None, 'shipment_orders', ['shipment_id'], ['id'])

    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipment_id', sa.Integer(), nullable=True, comment='关联发货单'))
        batch_op.add_column(sa.Column('has_supply_contract', sa.Boolean(), server_default='false', nullable=False, comment='是否已生成开票合同'))
        batch_op.drop_constraint(batch_op.f('scm_delivery_contracts_customs_declaration_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'shipment_orders', ['shipment_id'], ['id'])
        batch_op.drop_column('customs_declaration_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customs_declaration_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('scm_delivery_contracts_customs_declaration_id_fkey'), 'customs_declarations', ['customs_declaration_id'], ['id'])
        batch_op.drop_column('has_supply_contract')
        batch_op.drop_column('shipment_id')

    with op.batch_alter_table('customs_declarations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shipment_id')

    op.drop_table('supplier_tax_invoices')
    op.drop_table('scm_supply_contract_items')
    op.drop_table('scm_supply_contracts')
    op.drop_table('shipment_order_items')
    op.drop_table('shipment_orders')
    # ### end Alembic commands ###
