"""extend_hscode_model

Revision ID: 81858438e615
Revises: 26750682da6c
Create Date: 2025-12-09 03:31:17.174177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81858438e615'
down_revision = '26750682da6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_hs_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_1', sa.String(length=20), nullable=True, comment='第一法定单位'))
        batch_op.add_column(sa.Column('unit_2', sa.String(length=20), nullable=True, comment='第二法定单位'))
        batch_op.add_column(sa.Column('default_transaction_unit', sa.String(length=20), nullable=True, comment='建议成交/申报单位'))
        batch_op.add_column(sa.Column('import_mfn_rate', sa.DECIMAL(precision=6, scale=4), nullable=True, comment='进口最惠国税率'))
        batch_op.add_column(sa.Column('import_general_rate', sa.DECIMAL(precision=6, scale=4), nullable=True, comment='进口普通税率'))
        batch_op.add_column(sa.Column('vat_rate', sa.DECIMAL(precision=6, scale=4), nullable=True, comment='增值税率'))
        batch_op.add_column(sa.Column('regulatory_code', sa.String(length=50), nullable=True, comment='监管条件代码'))
        batch_op.add_column(sa.Column('inspection_code', sa.String(length=50), nullable=True, comment='检验检疫类别'))
        batch_op.add_column(sa.Column('elements', sa.Text(), nullable=True, comment='申报要素'))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True, comment='备注'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=20),
               comment='HS编码(10位)',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               comment='商品名称',
               existing_nullable=False)
        batch_op.alter_column('refund_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.DECIMAL(precision=6, scale=4),
               comment='出口退税率',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_hs_codes', schema=None) as batch_op:
        batch_op.alter_column('refund_rate',
               existing_type=sa.DECIMAL(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               comment=None,
               existing_comment='出口退税率',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='商品名称',
               existing_nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='HS编码(10位)',
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('note')
        batch_op.drop_column('elements')
        batch_op.drop_column('inspection_code')
        batch_op.drop_column('regulatory_code')
        batch_op.drop_column('vat_rate')
        batch_op.drop_column('import_general_rate')
        batch_op.drop_column('import_mfn_rate')
        batch_op.drop_column('default_transaction_unit')
        batch_op.drop_column('unit_2')
        batch_op.drop_column('unit_1')

    # ### end Alembic commands ###
