"""enhance customs declaration model

Revision ID: 824d924de4bb
Revises: 14f54365d002
Create Date: 2025-12-12 09:56:38.208071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '824d924de4bb'
down_revision = '14f54365d002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create new tables
    op.create_table('customs_declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pre_entry_no', sa.String(length=50), nullable=True, comment='预录入编号'),
    sa.Column('customs_no', sa.String(length=50), nullable=True, comment='海关编号'),
    sa.Column('entry_no', sa.String(length=50), nullable=True, comment='系统内部编号'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('internal_shipper_id', sa.Integer(), nullable=True, comment='境内发货人ID'),
    sa.Column('overseas_consignee', sa.String(length=255), nullable=True, comment='境外收货人'),
    sa.Column('export_date', sa.Date(), nullable=True, comment='出口日期'),
    sa.Column('declare_date', sa.Date(), nullable=True, comment='申报日期'),
    sa.Column('filing_no', sa.String(length=100), nullable=True, comment='备案号'),
    sa.Column('departure_port', sa.String(length=100), nullable=True, comment='出境关别/离境口岸'),
    sa.Column('entry_port', sa.String(length=100), nullable=True, comment='进境关别'),
    sa.Column('destination_country', sa.String(length=100), nullable=True, comment='运抵国(地区)'),
    sa.Column('trade_country', sa.String(length=100), nullable=True, comment='贸易国(地区)'),
    sa.Column('loading_port', sa.String(length=100), nullable=True, comment='指运港'),
    sa.Column('transport_mode', sa.String(length=50), nullable=True, comment='运输方式'),
    sa.Column('conveyance_ref', sa.String(length=100), nullable=True, comment='运输工具名称及航次号'),
    sa.Column('bill_of_lading_no', sa.String(length=100), nullable=True, comment='提运单号'),
    sa.Column('trade_mode', sa.String(length=50), nullable=True, comment='监管方式'),
    sa.Column('nature_of_exemption', sa.String(length=50), nullable=True, comment='征免性质'),
    sa.Column('license_no', sa.String(length=50), nullable=True, comment='许可证号'),
    sa.Column('contract_no', sa.String(length=50), nullable=True, comment='合同协议号'),
    sa.Column('transaction_mode', sa.String(length=20), nullable=True, comment='成交方式'),
    sa.Column('freight', sa.String(length=50), nullable=True, comment='运费'),
    sa.Column('insurance', sa.String(length=50), nullable=True, comment='保费'),
    sa.Column('incidental', sa.String(length=50), nullable=True, comment='杂费'),
    sa.Column('package_type', sa.String(length=50), nullable=True, comment='包装种类'),
    sa.Column('pack_count', sa.Integer(), nullable=True, comment='件数'),
    sa.Column('gross_weight', sa.DECIMAL(precision=18, scale=4), nullable=True, comment='毛重(千克)'),
    sa.Column('net_weight', sa.DECIMAL(precision=18, scale=4), nullable=True, comment='净重(千克)'),
    sa.Column('marks_and_notes', sa.Text(), nullable=True, comment='标记唛码及备注'),
    sa.Column('documents', sa.Text(), nullable=True, comment='随附单证'),
    sa.Column('fob_total', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('exchange_rate', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('logistics_provider', sa.String(length=100), nullable=True, comment='物流服务商'),
    sa.Column('shipping_date', sa.Date(), nullable=True, comment='发货日期'),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='来源: manual, excel_import, api'),
    sa.Column('source_file_url', sa.String(length=255), nullable=True, comment='原始文件路径'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['internal_shipper_id'], ['sys_companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_no')
    )
    op.create_table('customs_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('declaration_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('item_no', sa.Integer(), nullable=False, comment='项号'),
    sa.Column('hs_code', sa.String(length=20), nullable=True, comment='商品编号'),
    sa.Column('product_name_spec', sa.Text(), nullable=True, comment='商品名称及规格型号'),
    sa.Column('qty', sa.DECIMAL(precision=12, scale=4), nullable=False, comment='数量及单位1-数量'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='数量及单位1-单位'),
    sa.Column('qty_2', sa.DECIMAL(precision=12, scale=4), nullable=True, comment='数量及单位2-数量'),
    sa.Column('unit_2', sa.String(length=20), nullable=True, comment='数量及单位2-单位'),
    sa.Column('usd_unit_price', sa.DECIMAL(precision=18, scale=4), nullable=False, comment='单价'),
    sa.Column('usd_total', sa.DECIMAL(precision=18, scale=2), nullable=False, comment='总价'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='币制'),
    sa.Column('origin_country', sa.String(length=50), nullable=True, comment='原产国(地区)'),
    sa.Column('final_dest_country', sa.String(length=50), nullable=True, comment='最终目的国(地区)'),
    sa.Column('district_code', sa.String(length=20), nullable=True, comment='境内货源地'),
    sa.Column('exemption_way', sa.String(length=20), nullable=True, comment='征免'),
    sa.Column('supplier_id', sa.Integer(), nullable=True, comment='供应商ID'),
    sa.Column('sku', sa.String(length=100), nullable=True, comment='SKU编码(冗余)'),
    sa.Column('box_no', sa.String(length=50), nullable=True, comment='箱号'),
    sa.Column('net_weight', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='净重(KG)'),
    sa.Column('gross_weight', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='毛重(KG)'),
    sa.Column('rma_exchange_cost', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['declaration_id'], ['customs_declarations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['sys_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 2. Drop constraints on OLD tables FIRST
    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.drop_constraint('scm_delivery_contracts_customs_declaration_id_fkey', type_='foreignkey')

    with op.batch_alter_table('tax_refund_matches', schema=None) as batch_op:
        batch_op.drop_constraint('tax_refund_matches_customs_item_id_fkey', type_='foreignkey')

    # 3. Drop old tables
    op.drop_table('tax_customs_items')
    op.drop_table('tax_customs_declarations')

    # 4. Add constraints to NEW tables
    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'customs_declarations', ['customs_declaration_id'], ['id'])

    with op.batch_alter_table('tax_refund_matches', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'customs_items', ['customs_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Downgrade logic (Order also matters)
    
    # 1. Drop constraints on NEW tables
    with op.batch_alter_table('tax_refund_matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # 2. Recreate OLD tables
    op.create_table('tax_customs_declarations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tax_customs_declarations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('entry_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('export_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('destination_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('fob_total', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('exchange_rate', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('logistics_provider', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='物流服务商'),
    sa.Column('shipping_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='提单号/运单号'),
    sa.Column('shipping_date', sa.DATE(), autoincrement=False, nullable=True, comment='发货日期'),
    sa.Column('source_type', sa.VARCHAR(length=20), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=False, comment='来源: manual, excel_import, api'),
    sa.Column('source_file_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='原始文件路径'),
    sa.PrimaryKeyConstraint('id', name='tax_customs_declarations_pkey'),
    sa.UniqueConstraint('entry_no', name='tax_customs_declarations_entry_no_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('tax_customs_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('declaration_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qty', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('usd_unit_price', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('usd_total', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('rma_exchange_cost', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='供应商ID'),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='SKU编码(冗余)'),
    sa.Column('box_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='箱号'),
    sa.Column('net_weight', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True, comment='净重(KG)'),
    sa.Column('gross_weight', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True, comment='毛重(KG)'),
    sa.ForeignKeyConstraint(['declaration_id'], ['tax_customs_declarations.id'], name='tax_customs_items_declaration_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='tax_customs_items_product_id_fkey'),
    sa.ForeignKeyConstraint(['supplier_id'], ['sys_suppliers.id'], name='tax_customs_items_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tax_customs_items_pkey')
    )
    
    # 3. Add constraints back to OLD tables
    with op.batch_alter_table('tax_refund_matches', schema=None) as batch_op:
        batch_op.create_foreign_key('tax_refund_matches_customs_item_id_fkey', 'tax_customs_items', ['customs_item_id'], ['id'])

    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.create_foreign_key('scm_delivery_contracts_customs_declaration_id_fkey', 'tax_customs_declarations', ['customs_declaration_id'], ['id'])

    # 4. Drop NEW tables
    op.drop_table('customs_items')
    op.drop_table('customs_declarations')
    # ### end Alembic commands ###
