"""refactor payment terms

Revision ID: 87b3d16416ed
Revises: df8b29c2e1c8
Create Date: 2025-11-29 08:04:32.466175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b3d16416ed'
down_revision = 'df8b29c2e1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_payment_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='条款代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='条款名称'),
    sa.Column('baseline', sa.String(length=20), nullable=False, comment='基准日期'),
    sa.Column('days_offset', sa.Integer(), nullable=False, comment='偏移天数'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('fin_bank_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('counterparty_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('counterparty_account', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('reference_no', sa.String(length=100), nullable=True, comment='银行流水号'))
        batch_op.add_column(sa.Column('reconciled', sa.Integer(), nullable=False))
        batch_op.drop_column('counter_party')
        batch_op.drop_column('digest')

    with op.batch_alter_table('fin_payment_pool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True, comment='预计付款日'))
        batch_op.alter_column('soa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.INTEGER(),
               comment='优先级 0-100',
               existing_nullable=False)

    with op.batch_alter_table('fin_payment_reconciles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('soa_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.drop_constraint(batch_op.f('fin_payment_reconciles_payment_request_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fin_payment_reconciles_bank_transaction_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'fin_purchase_soas', ['soa_id'], ['id'])
        batch_op.create_foreign_key(None, 'fin_bank_transactions', ['transaction_id'], ['id'])
        batch_op.drop_column('reconciled_amount')
        batch_op.drop_column('payment_request_id')
        batch_op.drop_column('bank_transaction_id')

    with op.batch_alter_table('fin_payment_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('beneficiary_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('beneficiary_account', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('beneficiary_bank', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.drop_column('total_pay_amount')
        batch_op.drop_column('bank_account')

    with op.batch_alter_table('fin_purchase_soa_details', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='本期对账金额',
               existing_nullable=False)
        batch_op.drop_column('allocated_payment')

    with op.batch_alter_table('fin_purchase_soas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('period_end', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.drop_column('paid_amount')
        batch_op.drop_column('invoiced_amount')

    with op.batch_alter_table('fin_supply_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_no', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('reconciled_amount', sa.DECIMAL(precision=18, scale=2), nullable=False, comment='已纳入对账单金额'))
        batch_op.add_column(sa.Column('paid_amount', sa.DECIMAL(precision=18, scale=2), nullable=False, comment='实付金额'))
        batch_op.create_index(batch_op.f('ix_fin_supply_contracts_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_unique_constraint(None, ['l1_contract_id'])
        batch_op.drop_column('invoice_name')
        batch_op.drop_column('invoice_model')
        batch_op.drop_column('amount')

    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_term_id', sa.Integer(), nullable=True, comment='付款条款ID'))
        batch_op.alter_column('payment_terms',
               existing_type=sa.VARCHAR(length=100),
               comment='付款条款(快照)',
               existing_comment='付款条款',
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'sys_payment_terms', ['payment_term_id'], ['id'])

    with op.batch_alter_table('sys_suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_term_id', sa.Integer(), nullable=True, comment='默认付款条款ID'))
        batch_op.alter_column('payment_terms',
               existing_type=sa.VARCHAR(length=100),
               comment='付款条款(旧字段/快照)',
               existing_comment='付款条款',
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'sys_payment_terms', ['payment_term_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_suppliers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('payment_terms',
               existing_type=sa.VARCHAR(length=100),
               comment='付款条款',
               existing_comment='付款条款(旧字段/快照)',
               existing_nullable=True)
        batch_op.drop_column('payment_term_id')

    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('payment_terms',
               existing_type=sa.VARCHAR(length=100),
               comment='付款条款',
               existing_comment='付款条款(快照)',
               existing_nullable=True)
        batch_op.drop_column('payment_term_id')

    with op.batch_alter_table('fin_supply_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('invoice_model', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('invoice_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_fin_supply_contracts_supplier_id'))
        batch_op.drop_column('paid_amount')
        batch_op.drop_column('reconciled_amount')
        batch_op.drop_column('status')
        batch_op.drop_column('currency')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('contract_no')

    with op.batch_alter_table('fin_purchase_soas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoiced_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('paid_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('status')
        batch_op.drop_column('currency')
        batch_op.drop_column('period_end')
        batch_op.drop_column('period_start')

    with op.batch_alter_table('fin_purchase_soa_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allocated_payment', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False))
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment=None,
               existing_comment='本期对账金额',
               existing_nullable=False)

    with op.batch_alter_table('fin_payment_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_pay_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('approved_by')
        batch_op.drop_column('status')
        batch_op.drop_column('beneficiary_bank')
        batch_op.drop_column('beneficiary_account')
        batch_op.drop_column('beneficiary_name')
        batch_op.drop_column('currency')
        batch_op.drop_column('total_amount')

    with op.batch_alter_table('fin_payment_reconciles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_transaction_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('payment_request_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('reconciled_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fin_payment_reconciles_bank_transaction_id_fkey'), 'fin_bank_transactions', ['bank_transaction_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fin_payment_reconciles_payment_request_id_fkey'), 'fin_payment_requests', ['payment_request_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('amount')
        batch_op.drop_column('soa_id')
        batch_op.drop_column('transaction_id')

    with op.batch_alter_table('fin_payment_pool', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='优先级 0-100',
               existing_nullable=False)
        batch_op.alter_column('soa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('due_date')
        batch_op.drop_column('currency')

    with op.batch_alter_table('fin_bank_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('digest', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('counter_party', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('reconciled')
        batch_op.drop_column('reference_no')
        batch_op.drop_column('description')
        batch_op.drop_column('counterparty_account')
        batch_op.drop_column('counterparty_name')
        batch_op.drop_column('currency')

    op.drop_table('sys_payment_terms')
    # ### end Alembic commands ###
