"""将 attachment_ids 从 ARRAY 改为 JSON 类型

Revision ID: 8a2f32b22696
Revises: logistics_finance_v2
Create Date: 2025-12-20 06:38:21.202094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a2f32b22696'
down_revision = 'logistics_finance_v2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_center', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_dc_archived'))
        batch_op.drop_index(batch_op.f('idx_dc_audit_status'))
        batch_op.drop_index(batch_op.f('idx_dc_business_no'))
        batch_op.drop_index(batch_op.f('idx_dc_business_type_id'))
        batch_op.drop_index(batch_op.f('idx_dc_uploaded_by'))

    with op.batch_alter_table('logistics_payments', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_comment='币种',
               existing_server_default=sa.text("'CNY'::character varying"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_comment='状态',
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_lp_statement_id'))
        batch_op.drop_index(batch_op.f('idx_lp_status'))
        batch_op.drop_constraint(batch_op.f('logistics_payments_payment_pool_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('logistics_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_lp_is_active'))
        batch_op.drop_index(batch_op.f('idx_lp_provider_name'))

    with op.batch_alter_table('logistics_statements', schema=None) as batch_op:
        batch_op.alter_column('statement_period_start',
               existing_type=sa.DATE(),
               nullable=False,
               existing_comment='对账周期-开始')
        batch_op.alter_column('statement_period_end',
               existing_type=sa.DATE(),
               nullable=False,
               existing_comment='对账周期-结束')
        batch_op.alter_column('total_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               comment='对账总额',
               existing_comment='总金额')
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_comment='币种',
               existing_server_default=sa.text("'CNY'::character varying"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_comment='状态',
               existing_server_default=sa.text("'draft'::character varying"))
        batch_op.alter_column('confirmed_by_id',
               existing_type=sa.INTEGER(),
               comment='业务确认人(物流专员)',
               existing_comment='确认人ID',
               existing_nullable=True)
        batch_op.alter_column('attachment_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.JSON(),
               existing_comment='对账单附件ID列表（凭证中心）',
               existing_nullable=True)
        batch_op.alter_column('shipment_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='[DEPRECATED] 发货单ID，新版本使用多对多关联')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_ls_provider_id'))
        batch_op.drop_index(batch_op.f('idx_ls_shipment_id'))
        batch_op.drop_index(batch_op.f('idx_ls_status'))
        batch_op.drop_constraint(batch_op.f('logistics_statements_shipment_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('shipment_logistics_services', schema=None) as batch_op:
        batch_op.alter_column('shipment_id',
               existing_type=sa.INTEGER(),
               comment='发货单ID',
               existing_nullable=False)
        batch_op.alter_column('logistics_provider_id',
               existing_type=sa.INTEGER(),
               comment='物流服务商ID',
               existing_nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_comment='币种',
               existing_server_default=sa.text("'CNY'::character varying"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_comment='状态',
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_sls_provider_id'))
        batch_op.drop_index(batch_op.f('idx_sls_shipment_id'))
        batch_op.drop_index(batch_op.f('idx_sls_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_logistics_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_sls_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_sls_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_sls_provider_id'), ['logistics_provider_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='状态',
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_comment='币种',
               existing_server_default=sa.text("'CNY'::character varying"))
        batch_op.alter_column('logistics_provider_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='物流服务商ID',
               existing_nullable=False)
        batch_op.alter_column('shipment_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='发货单ID',
               existing_nullable=False)

    with op.batch_alter_table('logistics_statements', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('logistics_statements_shipment_id_fkey'), 'shipment_orders', ['shipment_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_ls_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_ls_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ls_provider_id'), ['logistics_provider_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('shipment_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='[DEPRECATED] 发货单ID，新版本使用多对多关联')
        batch_op.alter_column('attachment_ids',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_comment='对账单附件ID列表（凭证中心）',
               existing_nullable=True)
        batch_op.alter_column('confirmed_by_id',
               existing_type=sa.INTEGER(),
               comment='确认人ID',
               existing_comment='业务确认人(物流专员)',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='状态',
               existing_server_default=sa.text("'draft'::character varying"))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_comment='币种',
               existing_server_default=sa.text("'CNY'::character varying"))
        batch_op.alter_column('total_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               comment='总金额',
               existing_comment='对账总额')
        batch_op.alter_column('statement_period_end',
               existing_type=sa.DATE(),
               nullable=True,
               existing_comment='对账周期-结束')
        batch_op.alter_column('statement_period_start',
               existing_type=sa.DATE(),
               nullable=True,
               existing_comment='对账周期-开始')

    with op.batch_alter_table('logistics_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_lp_provider_name'), ['provider_name'], unique=False)
        batch_op.create_index(batch_op.f('idx_lp_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('logistics_payments', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('logistics_payments_payment_pool_id_fkey'), 'fin_payment_pool', ['payment_pool_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_lp_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_lp_statement_id'), ['statement_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='状态',
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_comment='币种',
               existing_server_default=sa.text("'CNY'::character varying"))

    with op.batch_alter_table('document_center', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_dc_uploaded_by'), ['uploaded_by_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_dc_business_type_id'), ['business_type', 'business_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_dc_business_no'), ['business_no'], unique=False)
        batch_op.create_index(batch_op.f('idx_dc_audit_status'), ['audit_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_dc_archived'), ['archived'], unique=False)

    # ### end Alembic commands ###
