"""添加发货单物流服务明细表

Revision ID: 91c4ca475d77
Revises: 20251219_logistics_doc
Create Date: 2025-12-19 15:28:55.838051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c4ca475d77'
down_revision = '20251219_logistics_doc'
branch_labels = None
depends_on = None


def upgrade():
    # 创建 shipment_logistics_services 表
    op.create_table(
        'shipment_logistics_services',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('shipment_id', sa.Integer(), nullable=False),
        sa.Column('logistics_provider_id', sa.Integer(), nullable=False),
        sa.Column('service_type', sa.String(length=50), nullable=False, comment='服务类型'),
        sa.Column('service_description', sa.Text(), comment='服务描述'),
        sa.Column('estimated_amount', sa.DECIMAL(18, 2), comment='预估费用'),
        sa.Column('actual_amount', sa.DECIMAL(18, 2), comment='实际费用'),
        sa.Column('currency', sa.String(length=10), server_default='CNY', comment='币种'),
        sa.Column('payment_method', sa.String(length=20), comment='付款方式'),
        sa.Column('service_voucher_id', sa.Integer(), comment='服务凭证ID'),
        sa.Column('payment_voucher_id', sa.Integer(), comment='付款凭证ID'),
        sa.Column('status', sa.String(length=20), server_default='pending', comment='状态'),
        sa.Column('confirmed_at', sa.DateTime(), comment='确认时间'),
        sa.Column('reconciled_at', sa.DateTime(), comment='对账时间'),
        sa.Column('paid_at', sa.DateTime(), comment='付款时间'),
        sa.Column('notes', sa.Text(), comment='备注'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), onupdate=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['shipment_id'], ['shipment_orders.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['logistics_provider_id'], ['logistics_providers.id']),
        sa.ForeignKeyConstraint(['service_voucher_id'], ['document_center.id']),
        sa.ForeignKeyConstraint(['payment_voucher_id'], ['document_center.id']),
    )
    
    # 创建索引
    op.create_index('idx_sls_shipment_id', 'shipment_logistics_services', ['shipment_id'])
    op.create_index('idx_sls_provider_id', 'shipment_logistics_services', ['logistics_provider_id'])
    op.create_index('idx_sls_status', 'shipment_logistics_services', ['status'])
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_orders', schema=None) as batch_op:
        batch_op.alter_column('total_goods_value',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='货物总价值 [DEPRECATED: 从商品明细计算]',
               existing_comment='货物总价值',
               existing_nullable=True)
        batch_op.alter_column('declared_value',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='申报价值 [DEPRECATED: 从报关单获取]',
               existing_comment='申报价值',
               existing_nullable=True)
        batch_op.alter_column('vat_number',
               existing_type=sa.VARCHAR(length=50),
               comment='VAT税号 [DEPRECATED: 从公司/收货人主表获取]',
               existing_comment='VAT税号',
               existing_nullable=True)
        batch_op.alter_column('tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment='税率 [DEPRECATED: 从税务配置获取]',
               existing_comment='税率',
               existing_nullable=True)
        batch_op.alter_column('estimated_tax',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='预估税费 [DEPRECATED: 从税务系统获取]',
               existing_comment='预估税费',
               existing_nullable=True)
        batch_op.alter_column('actual_tax',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='实际税费 [DEPRECATED: 从税务系统获取]',
               existing_comment='实际税费',
               existing_nullable=True)
        batch_op.alter_column('total_purchase_cost',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='采购总成本 [DEPRECATED: 从采购明细汇总]',
               existing_comment='采购总成本(从采购明细汇总)',
               existing_nullable=True)
        batch_op.alter_column('profit_margin',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               comment='利润率(%) [DEPRECATED: 从财务系统计算]',
               existing_comment='利润率(%)',
               existing_nullable=True)
        batch_op.alter_column('cost_allocation_method',
               existing_type=sa.VARCHAR(length=20),
               comment='成本分摊方式 [DEPRECATED: 从财务配置获取]',
               existing_comment='成本分摊方式(volume/weight/quantity/value)',
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='总金额（不含税）[DEPRECATED: 从采购明细计算]',
               existing_comment='总金额（不含税）',
               existing_nullable=True)
        batch_op.alter_column('total_tax_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='总税额 [DEPRECATED: 从报关单获取]',
               existing_comment='总税额',
               existing_nullable=True)
        batch_op.alter_column('total_amount_with_tax',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='含税总金额 [DEPRECATED: 从采购+报关单计算]',
               existing_comment='含税总金额',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # 删除索引
    op.drop_index('idx_sls_status', table_name='shipment_logistics_services')
    op.drop_index('idx_sls_provider_id', table_name='shipment_logistics_services')
    op.drop_index('idx_sls_shipment_id', table_name='shipment_logistics_services')
    
    # 删除表
    op.drop_table('shipment_logistics_services')
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_orders', schema=None) as batch_op:
        batch_op.alter_column('total_amount_with_tax',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='含税总金额',
               existing_comment='含税总金额 [DEPRECATED: 从采购+报关单计算]',
               existing_nullable=True)
        batch_op.alter_column('total_tax_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='总税额',
               existing_comment='总税额 [DEPRECATED: 从报关单获取]',
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='总金额（不含税）',
               existing_comment='总金额（不含税）[DEPRECATED: 从采购明细计算]',
               existing_nullable=True)
        batch_op.alter_column('cost_allocation_method',
               existing_type=sa.VARCHAR(length=20),
               comment='成本分摊方式(volume/weight/quantity/value)',
               existing_comment='成本分摊方式 [DEPRECATED: 从财务配置获取]',
               existing_nullable=True)
        batch_op.alter_column('profit_margin',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               comment='利润率(%)',
               existing_comment='利润率(%) [DEPRECATED: 从财务系统计算]',
               existing_nullable=True)
        batch_op.alter_column('total_purchase_cost',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='采购总成本(从采购明细汇总)',
               existing_comment='采购总成本 [DEPRECATED: 从采购明细汇总]',
               existing_nullable=True)
        batch_op.alter_column('actual_tax',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='实际税费',
               existing_comment='实际税费 [DEPRECATED: 从税务系统获取]',
               existing_nullable=True)
        batch_op.alter_column('estimated_tax',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='预估税费',
               existing_comment='预估税费 [DEPRECATED: 从税务系统获取]',
               existing_nullable=True)
        batch_op.alter_column('tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment='税率',
               existing_comment='税率 [DEPRECATED: 从税务配置获取]',
               existing_nullable=True)
        batch_op.alter_column('vat_number',
               existing_type=sa.VARCHAR(length=50),
               comment='VAT税号',
               existing_comment='VAT税号 [DEPRECATED: 从公司/收货人主表获取]',
               existing_nullable=True)
        batch_op.alter_column('declared_value',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='申报价值',
               existing_comment='申报价值 [DEPRECATED: 从报关单获取]',
               existing_nullable=True)
        batch_op.alter_column('total_goods_value',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='货物总价值',
               existing_comment='货物总价值 [DEPRECATED: 从商品明细计算]',
               existing_nullable=True)

    with op.batch_alter_table('logistics_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_lp_provider_name'), ['provider_name'], unique=False)
        batch_op.create_index(batch_op.f('idx_lp_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('document_center', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_dc_uploaded_by'), ['uploaded_by_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_dc_business_type_id'), ['business_type', 'business_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_dc_business_no'), ['business_no'], unique=False)
        batch_op.create_index(batch_op.f('idx_dc_audit_status'), ['audit_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_dc_archived'), ['archived'], unique=False)

    # ### end Alembic commands ###
