"""Add module resource action to Permission

Revision ID: 9dd88b803895
Revises: cebef3dd038a
Create Date: 2025-11-22 14:31:42.453818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd88b803895'
down_revision = 'cebef3dd038a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module', sa.String(length=50), nullable=False, server_default='系统管理'))
        batch_op.add_column(sa.Column('resource', sa.String(length=50), nullable=False, server_default='通用'))
        batch_op.add_column(sa.Column('action', sa.String(length=50), nullable=False, server_default='view'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_column('action')
        batch_op.drop_column('resource')
        batch_op.drop_column('module')

    # ### end Alembic commands ###
