"""添加装箱明细件数字段pack_count

Revision ID: a408719a2f2c
Revises: 49a7955f3095
Create Date: 2025-12-18 01:57:52.093660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a408719a2f2c'
down_revision = '49a7955f3095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declaration_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pack_count', sa.Integer(), nullable=True, comment='件数（一箱多件）'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declaration_items', schema=None) as batch_op:
        batch_op.drop_column('pack_count')

    # ### end Alembic commands ###
