"""change freight insurance incidental to decimal

Revision ID: a7e668414799
Revises: fdeb2967a7ea
Create Date: 2025-12-16 14:49:32.662978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e668414799'
down_revision = 'fdeb2967a7ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declarations', schema=None) as batch_op:
        # Use REGEX to extract the numeric part. 
        # Pattern: matches the first sequence of digits/dots
        # Example: 'USD/200/3' -> 200, '500' -> 500
        batch_op.alter_column('freight',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DECIMAL(precision=18, scale=4),
               existing_comment='运费',
               existing_nullable=True,
               postgresql_using="NULLIF(regexp_replace(freight, '[^0-9.]', '', 'g'), '')::numeric(18,4)")
        batch_op.alter_column('insurance',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DECIMAL(precision=18, scale=4),
               existing_comment='保费',
               existing_nullable=True,
               postgresql_using="NULLIF(regexp_replace(insurance, '[^0-9.]', '', 'g'), '')::numeric(18,4)")
        batch_op.alter_column('incidental',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DECIMAL(precision=18, scale=4),
               existing_comment='杂费',
               existing_nullable=True,
               postgresql_using="NULLIF(regexp_replace(incidental, '[^0-9.]', '', 'g'), '')::numeric(18,4)")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declarations', schema=None) as batch_op:
        batch_op.alter_column('incidental',
               existing_type=sa.DECIMAL(precision=18, scale=4),
               type_=sa.VARCHAR(length=50),
               existing_comment='杂费',
               existing_nullable=True)
        batch_op.alter_column('insurance',
               existing_type=sa.DECIMAL(precision=18, scale=4),
               type_=sa.VARCHAR(length=50),
               existing_comment='保费',
               existing_nullable=True)
        batch_op.alter_column('freight',
               existing_type=sa.DECIMAL(precision=18, scale=4),
               type_=sa.VARCHAR(length=50),
               existing_comment='运费',
               existing_nullable=True)

    # ### end Alembic commands ###
