"""扩展采购主体字段

Revision ID: a8d2399048a7
Revises: f88500c72423
Create Date: 2025-11-26 00:03:59.827376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8d2399048a7'
down_revision = 'f88500c72423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: 添加新字段（先设置为 nullable）
    with op.batch_alter_table('sys_companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legal_name', sa.String(length=200), nullable=True, comment='法定名称'))
        batch_op.add_column(sa.Column('short_name', sa.String(length=100), nullable=True, comment='简称'))
        batch_op.add_column(sa.Column('english_name', sa.String(length=200), nullable=True, comment='英文名称'))
        batch_op.add_column(sa.Column('company_type', sa.String(length=50), nullable=True, comment='公司类型'))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True, comment='状态'))
        batch_op.add_column(sa.Column('unified_social_credit_code', sa.String(length=18), nullable=True, comment='统一社会信用代码'))
        batch_op.add_column(sa.Column('business_license_no', sa.String(length=50), nullable=True, comment='营业执照注册号'))
        batch_op.add_column(sa.Column('business_license_issue_date', sa.Date(), nullable=True, comment='营业执照发证日期'))
        batch_op.add_column(sa.Column('business_license_expiry_date', sa.Date(), nullable=True, comment='营业执照有效期'))
        batch_op.add_column(sa.Column('business_scope', sa.Text(), nullable=True, comment='经营范围'))
        batch_op.add_column(sa.Column('registered_address', sa.String(length=500), nullable=True, comment='注册地址'))
        batch_op.add_column(sa.Column('business_address', sa.String(length=500), nullable=True, comment='经营地址'))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True, comment='邮政编码'))
        batch_op.add_column(sa.Column('contact_person', sa.String(length=50), nullable=True, comment='联系人'))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=50), nullable=True, comment='联系电话'))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=100), nullable=True, comment='联系邮箱'))
        batch_op.add_column(sa.Column('fax', sa.String(length=50), nullable=True, comment='传真'))
        batch_op.add_column(sa.Column('bank_accounts', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='银行账户列表'))
        batch_op.add_column(sa.Column('tax_rate', sa.Float(), nullable=True, comment='增值税率'))
        batch_op.add_column(sa.Column('tax_registration_date', sa.Date(), nullable=True, comment='税务登记日期'))
        batch_op.add_column(sa.Column('customs_code', sa.String(length=20), nullable=True, comment='海关编码'))
        batch_op.add_column(sa.Column('customs_registration_no', sa.String(length=50), nullable=True, comment='海关注册登记编号'))
        batch_op.add_column(sa.Column('inspection_code', sa.String(length=20), nullable=True, comment='检验检疫代码'))
        batch_op.add_column(sa.Column('foreign_trade_operator_code', sa.String(length=50), nullable=True, comment='对外贸易经营者备案号'))
        batch_op.add_column(sa.Column('forex_account', sa.String(length=100), nullable=True, comment='外汇账户'))
        batch_op.add_column(sa.Column('forex_registration_no', sa.String(length=50), nullable=True, comment='外汇登记证号'))
        batch_op.add_column(sa.Column('import_export_license_no', sa.String(length=50), nullable=True, comment='进出口许可证号'))
        batch_op.add_column(sa.Column('import_export_license_expiry', sa.Date(), nullable=True, comment='进出口许可证有效期'))
        batch_op.add_column(sa.Column('special_licenses', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='特殊资质列表'))
        batch_op.add_column(sa.Column('default_currency', sa.String(length=10), nullable=True, comment='默认币种'))
        batch_op.add_column(sa.Column('default_payment_term', sa.String(length=50), nullable=True, comment='默认付款条款'))
        batch_op.add_column(sa.Column('credit_limit', sa.DECIMAL(precision=15, scale=2), nullable=True, comment='信用额度'))
        batch_op.add_column(sa.Column('settlement_cycle', sa.Integer(), nullable=True, comment='结算周期（天）'))
        batch_op.add_column(sa.Column('cross_border_platform_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='跨境平台账号'))
        batch_op.add_column(sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='附件列表'))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True, comment='备注'))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'))
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'))
        batch_op.alter_column('tax_id',
               existing_type=sa.VARCHAR(length=50),
               comment='纳税人识别号',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    
    # Step 2: 迁移旧数据 (name -> legal_name, address -> registered_address, bank_info -> bank_accounts)
    op.execute("""
        UPDATE sys_companies 
        SET 
            legal_name = COALESCE(name, '未命名公司'),
            registered_address = address,
            bank_accounts = CASE 
                WHEN bank_info IS NOT NULL THEN jsonb_build_array(bank_info)
                ELSE NULL 
            END,
            status = 'active',
            default_currency = 'CNY'
        WHERE legal_name IS NULL
    """)
    
    # Step 3: 设置 legal_name 和 status 为 NOT NULL
    with op.batch_alter_table('sys_companies', schema=None) as batch_op:
        batch_op.alter_column('legal_name', nullable=False)
        batch_op.alter_column('status', nullable=False)
        batch_op.create_unique_constraint('uq_sys_companies_unified_social_credit_code', ['unified_social_credit_code'])
    
    # Step 4: 删除旧字段
    with op.batch_alter_table('sys_companies', schema=None) as batch_op:
        batch_op.drop_column('bank_info')
        batch_op.drop_column('name')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bank_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('tax_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='纳税人识别号',
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('notes')
        batch_op.drop_column('attachments')
        batch_op.drop_column('cross_border_platform_ids')
        batch_op.drop_column('settlement_cycle')
        batch_op.drop_column('credit_limit')
        batch_op.drop_column('default_payment_term')
        batch_op.drop_column('default_currency')
        batch_op.drop_column('special_licenses')
        batch_op.drop_column('import_export_license_expiry')
        batch_op.drop_column('import_export_license_no')
        batch_op.drop_column('forex_registration_no')
        batch_op.drop_column('forex_account')
        batch_op.drop_column('foreign_trade_operator_code')
        batch_op.drop_column('inspection_code')
        batch_op.drop_column('customs_registration_no')
        batch_op.drop_column('customs_code')
        batch_op.drop_column('tax_registration_date')
        batch_op.drop_column('tax_rate')
        batch_op.drop_column('bank_accounts')
        batch_op.drop_column('fax')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_person')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('business_address')
        batch_op.drop_column('registered_address')
        batch_op.drop_column('business_scope')
        batch_op.drop_column('business_license_expiry_date')
        batch_op.drop_column('business_license_issue_date')
        batch_op.drop_column('business_license_no')
        batch_op.drop_column('unified_social_credit_code')
        batch_op.drop_column('status')
        batch_op.drop_column('company_type')
        batch_op.drop_column('english_name')
        batch_op.drop_column('short_name')
        batch_op.drop_column('legal_name')

    # ### end Alembic commands ###
