"""Add field permission tables

Revision ID: adbc7811f138
Revises: 6cf03e4b387c
Create Date: 2025-11-23 07:47:32.178955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adbc7811f138'
down_revision = '6cf03e4b387c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_permission_metas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_key')
    )
    op.create_table('role_field_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_field_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_field_permissions_role_id'), ['role_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_field_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_field_permissions_role_id'))

    op.drop_table('role_field_permissions')
    op.drop_table('field_permission_metas')
    # ### end Alembic commands ###
