"""add_shipment_purchase_items_table

Revision ID: adf93da2b1d7
Revises: 57c8a8a82ef3
Create Date: 2025-12-18 12:06:04.257945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf93da2b1d7'
down_revision = '57c8a8a82ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_purchase_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_order_id', sa.Integer(), nullable=False, comment='发货单ID'),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True, comment='采购订单ID（关联采购模块）'),
    sa.Column('purchase_order_no', sa.String(length=50), nullable=True, comment='采购订单号'),
    sa.Column('purchase_line_id', sa.Integer(), nullable=True, comment='采购订单行ID'),
    sa.Column('product_variant_id', sa.Integer(), nullable=False, comment='商品变体ID'),
    sa.Column('sku', sa.String(length=100), nullable=False, comment='商品SKU'),
    sa.Column('product_name', sa.String(length=200), nullable=False, comment='商品名称'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='发货数量'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='单位'),
    sa.Column('purchase_unit_price', sa.Numeric(precision=15, scale=4), nullable=False, comment='采购单价'),
    sa.Column('purchase_total_price', sa.Numeric(precision=15, scale=4), nullable=False, comment='采购总价'),
    sa.Column('purchase_currency', sa.String(length=10), nullable=False, comment='采购币种'),
    sa.Column('supplier_id', sa.Integer(), nullable=True, comment='供应商ID'),
    sa.Column('supplier_name', sa.String(length=200), nullable=True, comment='供应商名称'),
    sa.Column('batch_no', sa.String(length=50), nullable=True, comment='采购批次号'),
    sa.Column('production_date', sa.Date(), nullable=True, comment='生产日期'),
    sa.Column('expire_date', sa.Date(), nullable=True, comment='过期日期'),
    sa.Column('warehouse_id', sa.Integer(), nullable=True, comment='仓库ID'),
    sa.Column('warehouse_location', sa.String(length=100), nullable=True, comment='仓库位置'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['shipment_order_id'], ['shipment_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_purchase_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_purchase_items_sku'), ['sku'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_purchase_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_purchase_items_sku'))

    op.drop_table('shipment_purchase_items')
    # ### end Alembic commands ###
