"""Update warehouse models v1.3

Revision ID: b0b1d6e65326
Revises: 6098d8fb0854
Create Date: 2025-12-10 08:54:29.825426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0b1d6e65326'
down_revision = '6098d8fb0854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('third_party_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_url', sa.String(length=255), nullable=False),
    sa.Column('app_key', sa.String(length=100), nullable=True),
    sa.Column('app_secret', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('config_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('stock_discrepancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('local_qty', sa.Integer(), nullable=False),
    sa.Column('remote_qty', sa.Integer(), nullable=False),
    sa.Column('diff_ratio', sa.Float(), nullable=True),
    sa.Column('diff_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolver_id', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('physical_quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('allocated_quantity', sa.Integer(), nullable=False),
    sa.Column('in_transit_quantity', sa.Integer(), nullable=False),
    sa.Column('damaged_quantity', sa.Integer(), nullable=False),
    sa.Column('batch_no', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocks_sku'), ['sku'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(length=30), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('biz_time', sa.DateTime(), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('batch_no', sa.String(length=50), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_locations.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_order_no'), ['order_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_sku'), ['sku'], unique=False)

    with op.batch_alter_table('warehouse_stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_stock_movements_order_no'))
        batch_op.drop_index(batch_op.f('ix_warehouse_stock_movements_sku'))

    op.drop_table('warehouse_stock_movements')
    op.drop_table('warehouse_stock_discrepancies')
    with op.batch_alter_table('warehouse_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_stocks_sku'))

    op.drop_table('warehouse_stocks')
    with op.batch_alter_table('stock_allocation_policies', schema=None) as batch_op:
        batch_op.drop_column('effective_from')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('created_at')
        batch_op.drop_column('effective_to')

    with op.batch_alter_table('warehouse_locations', schema=None) as batch_op:
        batch_op.drop_column('max_weight')
        batch_op.drop_column('max_volume')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('max_quantity')
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')

    with op.batch_alter_table('warehouse_product_group_items', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('warehouse_product_groups', schema=None) as batch_op:
        batch_op.drop_column('created_by')
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_product_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('warehouse_product_group_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))

    with op.batch_alter_table('warehouse_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('max_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('max_volume', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))

    with op.batch_alter_table('stock_allocation_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effective_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('effective_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    op.create_table('warehouse_stocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('physical_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('available_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('allocated_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('in_transit_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('damaged_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batch_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit_cost', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('warehouse_stocks_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('warehouse_stocks_pkey'))
    )
    with op.batch_alter_table('warehouse_stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_stocks_sku'), ['sku'], unique=False)

    op.create_table('warehouse_stock_discrepancies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('local_qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remote_qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diff_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('diff_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('discovered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resolver_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resolution', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('warehouse_stock_discrepancies_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('warehouse_stock_discrepancies_pkey'))
    )
    op.create_table('warehouse_stock_movements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('order_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('biz_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('quantity_delta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batch_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('unit_cost', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('exchange_rate', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_locations.id'], name=op.f('warehouse_stock_movements_location_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('warehouse_stock_movements_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('warehouse_stock_movements_pkey'))
    )
    with op.batch_alter_table('warehouse_stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_stock_movements_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_stock_movements_order_no'), ['order_no'], unique=False)

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_sku'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_order_no'))

    op.drop_table('stock_movements')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_sku'))

    op.drop_table('stocks')
    op.drop_table('stock_discrepancies')
    op.drop_table('third_party_services')
    # ### end Alembic commands ###
