"""add_version_and_lock_to_declaration

Revision ID: b0fa65203b52
Revises: 673c1d719b26
Create Date: 2025-12-12 15:10:39.680011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fa65203b52'
down_revision = '673c1d719b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declarations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1', comment='版本号'))
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=False, server_default='false', comment='是否锁定(已生成合同)'))
        batch_op.add_column(sa.Column('amendment_reason', sa.String(length=255), nullable=True, comment='修撤原因'))
        batch_op.add_column(sa.Column('amendment_status', sa.String(length=20), nullable=True, comment='修撤审批状态'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declarations', schema=None) as batch_op:
        batch_op.drop_column('amendment_status')
        batch_op.drop_column('amendment_reason')
        batch_op.drop_column('is_locked')
        batch_op.drop_column('version')

    # ### end Alembic commands ###
