"""add third_party_warehouse tables

Revision ID: b2d1f29e6fa2
Revises: b0b1d6e65326
Create Date: 2025-12-11 03:55:33.824999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d1f29e6fa2'
down_revision = 'b0b1d6e65326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('third_party_warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['third_party_services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'code', name='uix_service_warehouse_code')
    )
    with op.batch_alter_table('third_party_warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_third_party_warehouses_service_id'), ['service_id'], unique=False)

    op.create_table('third_party_sku_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('remote_sku', sa.String(length=100), nullable=False),
    sa.Column('local_sku', sa.String(length=100), nullable=False),
    sa.Column('quantity_ratio', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['third_party_services.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['third_party_warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('third_party_sku_mappings', schema=None) as batch_op:
        batch_op.create_index('idx_mapping_lookup', ['service_id', 'remote_sku', 'warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_third_party_sku_mappings_local_sku'), ['local_sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_third_party_sku_mappings_remote_sku'), ['remote_sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_third_party_sku_mappings_service_id'), ['service_id'], unique=False)

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('third_party_service_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('third_party_warehouse_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'third_party_services', ['third_party_service_id'], ['id'])
        batch_op.create_foreign_key(None, 'third_party_warehouses', ['third_party_warehouse_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('third_party_warehouse_id')
        batch_op.drop_column('third_party_service_id')

    with op.batch_alter_table('third_party_sku_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_third_party_sku_mappings_service_id'))
        batch_op.drop_index(batch_op.f('ix_third_party_sku_mappings_remote_sku'))
        batch_op.drop_index(batch_op.f('ix_third_party_sku_mappings_local_sku'))
        batch_op.drop_index('idx_mapping_lookup')

    op.drop_table('third_party_sku_mappings')
    with op.batch_alter_table('third_party_warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_third_party_warehouses_service_id'))

    op.drop_table('third_party_warehouses')
    # ### end Alembic commands ###
