"""添加商品明细的出口申报名称和海关申报单位字段

Revision ID: c3fe645260ed
Revises: adf93da2b1d7
Create Date: 2025-12-18 12:53:02.027514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3fe645260ed'
down_revision = 'adf93da2b1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('export_name', sa.String(length=255), nullable=True, comment='出口申报名称'))
        batch_op.add_column(sa.Column('customs_unit', sa.String(length=20), nullable=True, comment='海关申报单位'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_order_items', schema=None) as batch_op:
        batch_op.drop_column('customs_unit')
        batch_op.drop_column('export_name')

    # ### end Alembic commands ###
