"""add_table_warehouse_third_party_products

Revision ID: c65ee950e9f1
Revises: c4041798fdfe
Create Date: 2025-12-11 07:28:23.825734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c65ee950e9f1'
down_revision = 'c4041798fdfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_third_party_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('remote_sku', sa.String(length=100), nullable=False),
    sa.Column('remote_name', sa.String(length=200), nullable=False),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['warehouse_third_party_services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'remote_sku', name='uix_service_remote_sku')
    )
    with op.batch_alter_table('warehouse_third_party_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_third_party_products_remote_sku'), ['remote_sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_third_party_products_service_id'), ['service_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_third_party_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_third_party_products_service_id'))
        batch_op.drop_index(batch_op.f('ix_warehouse_third_party_products_remote_sku'))

    op.drop_table('warehouse_third_party_products')
    # ### end Alembic commands ###
