"""修改profit_margin字段精度

Revision ID: d7504d53bb1f
Revises: 141feba69c64
Create Date: 2025-12-19 03:29:39.234426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7504d53bb1f'
down_revision = '141feba69c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_orders', schema=None) as batch_op:
        batch_op.alter_column('is_factory_direct',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否工厂直发',
               existing_server_default=sa.text('false'))
        batch_op.alter_column('profit_margin',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.DECIMAL(precision=7, scale=2),
               comment='利润率(%)',
               existing_comment='利润率',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_orders', schema=None) as batch_op:
        batch_op.alter_column('profit_margin',
               existing_type=sa.DECIMAL(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=4),
               comment='利润率',
               existing_comment='利润率(%)',
               existing_nullable=True)
        batch_op.alter_column('is_factory_direct',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否工厂直发',
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###
