"""Enhance SysSupplier table

Revision ID: d818a0584eb8
Revises: a8d2399048a7
Create Date: 2025-11-26 04:14:48.392166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd818a0584eb8'
down_revision = 'a8d2399048a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add columns as nullable first
    with op.batch_alter_table('sys_suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=50), nullable=True, comment='供应商代码'))
        batch_op.add_column(sa.Column('supplier_type', sa.String(length=50), nullable=True, comment='类型'))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True, comment='状态'))
        batch_op.add_column(sa.Column('grade', sa.String(length=10), nullable=True, comment='等级'))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True, comment='国家/地区'))
        batch_op.add_column(sa.Column('province', sa.String(length=50), nullable=True, comment='省份'))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True, comment='城市'))
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True, comment='详细地址'))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True, comment='官网'))
        batch_op.add_column(sa.Column('primary_contact', sa.String(length=50), nullable=True, comment='首要联系人'))
        batch_op.add_column(sa.Column('primary_phone', sa.String(length=50), nullable=True, comment='联系电话'))
        batch_op.add_column(sa.Column('primary_email', sa.String(length=100), nullable=True, comment='Email'))
        batch_op.add_column(sa.Column('contacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='联系人列表'))
        batch_op.add_column(sa.Column('tax_id', sa.String(length=50), nullable=True, comment='税号/VAT号'))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True, comment='默认结算币种'))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True, comment='付款方式'))
        batch_op.add_column(sa.Column('bank_accounts', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='银行账户'))
        batch_op.add_column(sa.Column('lead_time_days', sa.Integer(), nullable=True, comment='平均交货天数'))
        batch_op.add_column(sa.Column('moq', sa.String(length=50), nullable=True, comment='最小起订量描述'))
        batch_op.add_column(sa.Column('purchase_uid', sa.Integer(), nullable=True, comment='负责采购员ID'))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True, comment='备注'))
        batch_op.add_column(sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='标签'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        
    # 2. Data Migration: Fill default values for existing records
    op.execute("UPDATE sys_suppliers SET code = 'SUP-' || id WHERE code IS NULL")
    op.execute("UPDATE sys_suppliers SET supplier_type = 'manufacturer' WHERE supplier_type IS NULL")
    op.execute("UPDATE sys_suppliers SET status = 'active' WHERE status IS NULL")
    op.execute("UPDATE sys_suppliers SET currency = 'CNY' WHERE currency IS NULL")
    op.execute("UPDATE sys_suppliers SET contacts = '[]'::jsonb WHERE contacts IS NULL")
    op.execute("UPDATE sys_suppliers SET bank_accounts = '[]'::jsonb WHERE bank_accounts IS NULL")
    op.execute("UPDATE sys_suppliers SET tags = '[]'::jsonb WHERE tags IS NULL")

    # 3. Set NOT NULL constraints
    with op.batch_alter_table('sys_suppliers', schema=None) as batch_op:
        batch_op.alter_column('code', nullable=False)
        batch_op.alter_column('supplier_type', nullable=False)
        batch_op.alter_column('status', nullable=False)
        batch_op.alter_column('currency', nullable=False)
        batch_op.alter_column('contacts', nullable=False)
        batch_op.alter_column('bank_accounts', nullable=False)
        batch_op.alter_column('tags', nullable=False)
        
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               comment='供应商名称',
               existing_nullable=False)
        batch_op.alter_column('short_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               comment='简称',
               existing_nullable=True)
        batch_op.alter_column('payment_terms',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               comment='付款条款',
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['code'])
        batch_op.drop_column('bank_details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('payment_terms',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='付款条款',
               existing_nullable=True)
        batch_op.alter_column('short_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='简称',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='供应商名称',
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('tags')
        batch_op.drop_column('notes')
        batch_op.drop_column('purchase_uid')
        batch_op.drop_column('moq')
        batch_op.drop_column('lead_time_days')
        batch_op.drop_column('bank_accounts')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('currency')
        batch_op.drop_column('tax_id')
        batch_op.drop_column('contacts')
        batch_op.drop_column('primary_email')
        batch_op.drop_column('primary_phone')
        batch_op.drop_column('primary_contact')
        batch_op.drop_column('website')
        batch_op.drop_column('address')
        batch_op.drop_column('city')
        batch_op.drop_column('province')
        batch_op.drop_column('country')
        batch_op.drop_column('grade')
        batch_op.drop_column('status')
        batch_op.drop_column('supplier_type')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
