"""add customs product library

Revision ID: d820af9f5fd7
Revises: 7e1b6cf76e4c
Create Date: 2025-12-17 08:30:02.427347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd820af9f5fd7'
down_revision = '7e1b6cf76e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customs_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='报关通用名称'),
    sa.Column('hs_code', sa.String(length=50), nullable=False, comment='海关编码'),
    sa.Column('rebate_rate', sa.DECIMAL(precision=6, scale=4), nullable=True, comment='退税率'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='申报单位'),
    sa.Column('elements', sa.Text(), nullable=True, comment='申报要素模板'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注说明'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customs_product_id', sa.Integer(), nullable=True, comment='关联报关品类'))
        batch_op.add_column(sa.Column('customs_name_cn', sa.String(length=200), nullable=True, comment='报关中文名称(覆盖)'))
        batch_op.add_column(sa.Column('customs_name_en', sa.String(length=200), nullable=True, comment='报关英文名称(覆盖)'))
        batch_op.create_foreign_key(None, 'customs_products', ['customs_product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('customs_name_en')
        batch_op.drop_column('customs_name_cn')
        batch_op.drop_column('customs_product_id')

    op.drop_table('customs_products')
    # ### end Alembic commands ###
