"""add payment info to contracts

Revision ID: df8b29c2e1c8
Revises: 57fa1a77cf8e
Create Date: 2025-11-29 06:44:15.113399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8b29c2e1c8'
down_revision = '57fa1a77cf8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_terms', sa.String(length=100), nullable=True, comment='付款条款'))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True, comment='付款方式'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payment_terms')

    # ### end Alembic commands ###
