"""add declaration elements

Revision ID: e099913b18c7
Revises: 824d924de4bb
Create Date: 2025-12-12 13:18:10.388065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e099913b18c7'
down_revision = '824d924de4bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('declaration_elements', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='申报要素键值对'))
        batch_op.add_column(sa.Column('element_string', sa.Text(), nullable=True, comment='申报要素拼接串'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_items', schema=None) as batch_op:
        batch_op.drop_column('element_string')
        batch_op.drop_column('declaration_elements')

    # ### end Alembic commands ###
