"""添加报关单明细英文名称字段product_name_en_spec

Revision ID: e9af8e1a6e56
Revises: 0db29e5b5489
Create Date: 2025-12-18 03:14:24.040265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9af8e1a6e56'
down_revision = '0db29e5b5489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declaration_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name_en_spec', sa.Text(), nullable=True, comment='商品英文名称及规格型号'))
        batch_op.alter_column('product_name_spec',
               existing_type=sa.TEXT(),
               comment='商品名称及规格型号（中文）',
               existing_comment='商品名称及规格型号',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declaration_items', schema=None) as batch_op:
        batch_op.alter_column('product_name_spec',
               existing_type=sa.TEXT(),
               comment='商品名称及规格型号',
               existing_comment='商品名称及规格型号（中文）',
               existing_nullable=True)
        batch_op.drop_column('product_name_en_spec')

    # ### end Alembic commands ###
