"""Add name_en and description to attribute_definitions

Revision ID: ee78dd561c3a
Revises: 3378631318c7
Create Date: 2025-12-05 09:27:50.545726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee78dd561c3a'
down_revision = '3378631318c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attribute_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=100), nullable=True, comment='英文名称'))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True, comment='属性详细描述'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attribute_definitions', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('name_en')

    # ### end Alembic commands ###
