"""Add supplier_snapshot to ScmDeliveryContract

Revision ID: f21f83573982
Revises: 87b3d16416ed
Create Date: 2025-11-30 03:20:07.093483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f21f83573982'
down_revision = '87b3d16416ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='供应商快照'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scm_delivery_contracts', schema=None) as batch_op:
        batch_op.drop_column('supplier_snapshot')

    # ### end Alembic commands ###
