"""remove_circular_fk_shipment_declaration

Revision ID: f48b1719e2d2
Revises: 80619c8bee36
Create Date: 2025-12-17 15:51:27.534979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48b1719e2d2'
down_revision = '80619c8bee36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('shipment_orders_customs_declaration_id_fkey'), type_='foreignkey')
        batch_op.drop_column('customs_declaration_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customs_declaration_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='关联报关单'))
        batch_op.create_foreign_key(batch_op.f('shipment_orders_customs_declaration_id_fkey'), 'customs_declarations', ['customs_declaration_id'], ['id'])

    # ### end Alembic commands ###
