"""add serc tables

Revision ID: f88500c72423
Revises: adbc7811f138
Create Date: 2025-11-25 06:09:47.330322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f88500c72423'
down_revision = 'adbc7811f138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fin_bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trans_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('counter_party', sa.String(length=100), nullable=False),
    sa.Column('digest', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fin_payment_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_no', sa.String(length=50), nullable=False),
    sa.Column('total_pay_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('bank_account', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_no')
    )
    op.create_table('sys_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('bank_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('safe_min', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('safe_max', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency')
    )
    op.create_table('sys_hs_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('refund_rate', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sys_suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('payment_terms', sa.String(length=50), nullable=True),
    sa.Column('bank_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_customs_declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_no', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('export_date', sa.Date(), nullable=True),
    sa.Column('destination_country', sa.String(length=100), nullable=True),
    sa.Column('fob_total', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('exchange_rate', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_no')
    )
    op.create_table('fin_payment_reconciles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_request_id', sa.Integer(), nullable=False),
    sa.Column('bank_transaction_id', sa.Integer(), nullable=False),
    sa.Column('reconciled_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['fin_bank_transactions.id'], ),
    sa.ForeignKeyConstraint(['payment_request_id'], ['fin_payment_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fin_purchase_soas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soa_no', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('total_payable', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('paid_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('invoiced_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('invoice_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['sys_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('soa_no')
    )
    op.create_table('scm_source_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_no', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('tracking_source', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['sys_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_no')
    )
    op.create_table('fin_payment_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soa_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['soa_id'], ['fin_purchase_soas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scm_delivery_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_no', sa.String(length=50), nullable=False),
    sa.Column('source_doc_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_doc_id'], ['scm_source_docs.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['sys_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_no')
    )
    op.create_table('tax_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_code', sa.String(length=50), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('amount_total', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('soa_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['soa_id'], ['fin_purchase_soas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_table('fin_purchase_soa_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soa_id', sa.Integer(), nullable=False),
    sa.Column('l1_contract_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('allocated_payment', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['l1_contract_id'], ['scm_delivery_contracts.id'], ),
    sa.ForeignKeyConstraint(['soa_id'], ['fin_purchase_soas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fin_supply_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('l1_contract_id', sa.Integer(), nullable=False),
    sa.Column('invoice_name', sa.String(length=200), nullable=False),
    sa.Column('invoice_model', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['l1_contract_id'], ['scm_delivery_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scm_delivery_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('l1_contract_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('confirmed_qty', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('total_price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['l1_contract_id'], ['scm_delivery_contracts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_customs_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('declaration_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('usd_unit_price', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('usd_total', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('rma_exchange_cost', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['declaration_id'], ['tax_customs_declarations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['tax_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_refund_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customs_item_id', sa.Integer(), nullable=False),
    sa.Column('invoice_item_id', sa.Integer(), nullable=False),
    sa.Column('matched_qty', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customs_item_id'], ['tax_customs_items.id'], ),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['tax_invoice_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('declared_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('declared_unit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('hs_code_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sys_hs_codes', ['hs_code_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hs_code_id')
        batch_op.drop_column('declared_unit')
        batch_op.drop_column('declared_name')

    op.drop_table('tax_refund_matches')
    op.drop_table('tax_invoice_items')
    op.drop_table('tax_customs_items')
    op.drop_table('scm_delivery_items')
    op.drop_table('fin_supply_contracts')
    op.drop_table('fin_purchase_soa_details')
    op.drop_table('tax_invoices')
    op.drop_table('scm_delivery_contracts')
    op.drop_table('fin_payment_pool')
    op.drop_table('scm_source_docs')
    op.drop_table('fin_purchase_soas')
    op.drop_table('fin_payment_reconciles')
    op.drop_table('tax_customs_declarations')
    op.drop_table('sys_suppliers')
    op.drop_table('sys_hs_codes')
    op.drop_table('sys_exchange_rates')
    op.drop_table('sys_companies')
    op.drop_table('fin_payment_requests')
    op.drop_table('fin_bank_transactions')
    # ### end Alembic commands ###
