"""add currency to customs_declaration

Revision ID: fdeb2967a7ea
Revises: 5804495c05ba
Create Date: 2025-12-16 14:27:59.245102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdeb2967a7ea'
down_revision = '5804495c05ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declarations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True, comment='成交币种'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declarations', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
