"""Add container_mode to CustomsDeclaration

Revision ID: fea4aae536ba
Revises: 4dc10e92afb2
Create Date: 2025-12-16 06:54:54.134552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea4aae536ba'
down_revision = '4dc10e92afb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declarations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container_mode', sa.String(length=20), nullable=True, comment='货柜模式: FCL(整柜), LCL(散货)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs_declarations', schema=None) as batch_op:
        batch_op.drop_column('container_mode')

    # ### end Alembic commands ###
